### ISSUE TITLE
Ability to set custom image version numbers

### ISSUE THREAD

**Issue by stackcv** [boxfuse/boxfuse-issues#101]
Feature request:

boxFuse command to allow specifying custom version numbers for the fused image and use that to create the final image.

_Example_:  
boxfuse fuse -image.version=34.223
Or
./gradle boxfuseFuse -Dboxfuse.imageversion=34.3223

Currently, it defaults to 0.1 always (or auto generated fallback version) . Tried changing the payload version but that doesn't affect the image version.

Current output from console:

`Images available locally:
+------------------------------------------+------------------------+-------+-----------------------------+---------------+---------+---------------------+
| Image                                    |        Payload         | Debug |           Runtime           |     Ports     |  Size   |    Generated at     |
+------------------------------------------+------------------------+-------+-----------------------------+---------------+---------+---------------------+
| myapp/myapp-rest:0.0.0.1469076293817 | myapp-rest-0.321.jar | false | Java 8.102.14 (Spring Boot) | https -> 8443, http -> 80 | 78317 K | 2016-07-21 10:14:53 |
+------------------------------------------+------------------------+-------+-----------------------------+---------------+---------+---------------------+
Total: 1
`

**Comment by axelfontaine** [comment]
This is already possible. The Boxfuse Gradle plugin will default to using the Gradle project version. You can override this by explicitely setting boxfuse.image to the app name and version you want. Example: `gradle boxfuseFuse -Dboxfuse.image=abc:123` to fuse version 123 of abc.

**Comment by stackcv** [comment]
Great. Thanks @axelfontaine going to try this.
I posted the issue because the documentation for fuse (with gradle) did not mention _image_ option, so I didn't know it existed. I referred to [https://boxfuse.com/docs/gradle/fuse](url)
