### ISSUE TITLE
Configure Logging per App

### ISSUE THREAD

**Issue by herder** [boxfuse/boxfuse-issues#104]
Instead of having to configure each app to send to a log aggregator, it would be convenient to be able to specify this as a component on an app, or possibly a whole environment.
This would allow us more direct feedback from an app's `stdout`, and not have to wait for the log aggregator to kick in.

I'd like to be able to specify log type (AWS/loggly/whatever), and then any properties required for a specific endpoint.

**Comment by axelfontaine** [comment]
:+1: 

We're finalizing CW Logs integration and are planning to add others after that.

**Comment by axelfontaine** [comment]
CloudWatch Logs support has now been released: https://boxfuse.com/blog/cloudwatch-logs

I'm closing this one for now. Please reopen issues for specific additional logging services if you need support for them
