### ISSUE TITLE
route53 concurrency: The request was rejected because Route 53 was still processing a prior request.

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#114]
I started two deployments at the same time and notices this issue:
It looks like amazon route53 does not allow concurrent changes to a zone:
http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/DNSLimitations.html

```
15:10:02.124 ERROR: Deployment of [...] failed in [...]: The request was rejected because Route 53 was still processing a prior request. (Service: AmazonRoute53; Status Code: 400; Error Code: PriorRequestNotComplete; Request ID: 07591582-8646-11e6-96a2-cb64e5d9cd85)
15:10:02.126 ERROR: Running jtheuer/wanderwalter [...] failed!
com.boxfuse.base.exception.BoxfuseException: Running [...] failed!
	at com.boxfuse.client.core.Boxfuse.run(SourceFile:624)
	at com.boxfuse.client.commandline.Main.run(Main.java:317)
	at com.boxfuse.client.commandline.Main.main(Main.java:100)
```
I think they refer to your boxfuse.io zone, so it might also happen when two different customers deploy at the same time.

Best,

Jan

**Comment by axelfontaine** [comment]
Thank you for reporting this. We have now rolled out multiple measures to both prevent and recover from this.
