### ISSUE TITLE
boxfuse delete [app]

### ISSUE THREAD

**Issue by tullo** [boxfuse/boxfuse-issues#118]
According to boxfuse cli det delete cmd should do the following

> delete [app]             Deletes an App in the Boxfuse Console

which it does not do.

`boxfuse destroy [app]` will delete the app as per https://boxfuse.com/docs/commands#destroy

I'd suggest to update the CLI help to reduce the confusion:
**destroy** [app]             Deletes an App in the Boxfuse Console

**Comment by axelfontaine** [comment]
Good catch! This has now been fixed in the latest client release.

Thanks!
