### ISSUE TITLE
Timeout for blue-green deployments

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#119]
I have an application that needs to prepare data in-memory before users can use it. Therefore I want to increase the timeout in blue-green deployments.

I set ```healthcheck.timeout=1200``` in the boxfuse configfile and run it with ```boxfuse -X```. I see the healthcheck value but later it times out:

```
15:33:32.091 healthcheck.timeout -> 1200 on start

[...]
15:46:59.993 ERROR: Deployment of ... failed in ...: Time out: ELB failed to put instances in service within 600 seconds.
```

Checking the timestamps, boxfuse didn't run for 1200 seconds. It looks like the property is ignored?

**Comment by axelfontaine** [comment]
Sorry about the trouble. This was indeed being ignored for ELB deployments. This has now been corrected and the fix has been deployed and is ready for you to use.

**Comment by jtheuer** [comment]
thanks for the quick fix!
