### ISSUE TITLE
Make maven plugin set environment variable with AMI id after convert

### ISSUE THREAD

**Issue by herder** [boxfuse/boxfuse-issues#123]
We'd like to try out different pipeline options, and a low-hanging fruit for this would be to enable an option to have access to the AMI id of the resulting image when converting via the Maven plugin.

Since we possibly want to make multiple images (for different regions), we should be able to specify which variable name the AMI id should be tied to.

Maybe something like:

```
 				<executions>
					<execution>
						<id>convert-image</id>
						<goals>
							<goal>convert</goal>
						</goals>
						<phase>install</phase>
						<configuration>
							<env>stage-eu-west-1</env>
							<image-export-name>IRELAND_AMI_IMAGE</image-export-name>
						</configuration>
					</execution>
					<execution>
						<id>convert-image</id>
						<goals>
							<goal>convert</goal>
						</goals>
						<phase>install</phase>
						<configuration>
							<env>stage-eu-central-1</env>
							<image-export-name>FRANKFURT_AMI_IMAGE</image-export-name>
						</configuration>
					</execution>
				</executions>
```

This could export the variables `IRELAND_AMI_IMAGE` and `FRANKFURT_AMI_IMAGE` with their respective AMI id:s.

**Comment by axelfontaine** [comment]
Currently `convert` only works with your default AWS region. I have raised an issue to automatically derive the region based on the specified environment: https://github.com/boxfuse/boxfuse-issues/issues/124

Instead of setting an environment variable, it would probably be better and more consistent to dynamically set a Maven property just like we are already doing with `boxfuse.image` (see https://boxfuse.com/docs/maven/convert). You could then use this to do whatever you want suing other Maven plugins.

What do you think?

**Comment by herder** [comment]
Ah, missed that one! Yes, I agree: setting a Maven property seems like a better option. 
But if we're doing multiple converts in the same build (when #124 is solved), we need some way to know which image ended up where, possibly by some naming convention of the property?

**Comment by axelfontaine** [comment]
What do you think of `boxfuse.ami.eu-west-1` , `boxfuse.ami.ap-southeast-2` , ... ?

**Comment by herder** [comment]
Looks good to me! 👍

**Comment by axelfontaine** [comment]
To stay consistent with the machine-readable output of https://boxfuse.com/docs/commandline/convert, we decided to go for `boxfuse.aws.ami.eu-west-1` , `boxfuse.aws.ami.ap-southeast-2`, ...  instead.

**Comment by axelfontaine** [comment]
This  has now been released as part of 1.23.0.1181.

The final properties are named like this: `boxfuse.aws.<region>.ami` See https://boxfuse.com/docs/maven/convert#dynamic-properties

**Comment by herder** [comment]
Awesome, that was fast! Cheers 👍

**Comment by axelfontaine** [comment]
It was a nice low-hanging fruit :-)

**Comment by herder** [comment]
The best kind of fruit :)
