### ISSUE TITLE
Ability to customize RDS instance name

### ISSUE THREAD

**Issue by superandrew** [boxfuse/boxfuse-issues#129]
Hi, right now when fuse creates resources on amazon, it creates with this naming convention

boxdb-superandrew-prod-<appname>

I wasn't able to understand how to change that. Is that possible? I changed my email in the account page but didn't find any reference on the configuration documentation.

**Comment by axelfontaine** [comment]
@superandrew This is not configurable. This is a globally namespaced resource within your account and we pick a suitable name that doesn't collide with any other DB. We actually do this for all kinds of resources (load balancers, security groups, log groups, ...).

Can you help me understand your use case better? Why is having a specific name important to you? Or is this purely a cosmetic preference?

**Comment by superandrew** [comment]
I work for a company, but my only option to login was to authenticate with Github. So that’s the first problem, since I want my billing to be for the company and not to “superandrew”. The second is cosmetic, and it is actually not a big deal, but, well boxlb-superandrew-prod-appname-******.eu-west-1.elb.amazonaws.com <http://eu-west-1.elb.amazonaws.com/> sounds a bit cheesy.

**Comment by axelfontaine** [comment]
What most companies do is sign up for a new company github account (it's free) and use that to log in to the Boxfuse Console.

The ELB name is also always mapped to a boxfuse.io domain. For example for an app named abc is the prod environment this would be abc-superandrew.boxfuse.io . In most realistic scenarios though you would probably want to register your own domain name and associate it via a CNAME record with the boxfuse.io domain that was created for you (or with the underlying ELB when using an ALIAS record on route 53). See https://boxfuse.com/docs/domains

**Comment by superandrew** [comment]
I'll do as you suggest, @axelfontaine . Thank you.
