### ISSUE TITLE
ERROR: Incomplete coordinates

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#134]
I am pretty certain this will be easily solvable, but the error message I am getting does not give me much guidance on the issue. 
`ERROR: Incomplete coordinates: ui`

What does this mean? I haven't tried deploying in 8 months. Since then I have upgraded my boxfuse version to the latest and used maven to deploy. Any ideas what this could be?

**Comment by axelfontaine** [comment]
Sorry about the rather cryptic error message. This means Boxfuse also requires the version of an image (example: ui:1.2.3) instead of just the app name (ui). Which Maven goal were you executing and which exact parameters did you use?

**Comment by forbode** [comment]
I hadn't touched this in a while so I forgot what to do apparently. I was using PUSH and didn't have an image name set in my Maven properties. Since I didn't set the image name Boxfuse threw the error. 
My suggestion is to refine the error message to include some form of indication that the "image" name might be missing.

**Comment by axelfontaine** [comment]
This has now been fixed in Boxfuse Client 1.24.1 

Push without a version now pushes the latest version available locally and the confusing error message has been reworded.
