### ISSUE TITLE
Version Numbers with Letters

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#135]
This is really a feature request. Typically in Maven builds or, for that matter, many java build systems, it is common to append "snapshot" or "release" after version numbers. Boxfuse will not accept this. Is that because you favor the idea of test vs production? Is it realistic to allow for this?

**Comment by axelfontaine** [comment]
There are two answers for this:

1. Snapshots are undefined states which does not match Boxfuse's concept of every image being uniquely referenceable by having a unique version. This is the reason why we automatically generate a fallback version in those cases.

2. Having letters in the version makes it harder to keep things machine-sortable in a way that makes sense (think "first", "fourth", "second", "third"). Sticking to the dotted number notation just makes things easier.

Did this answer your question?

**Comment by forbode** [comment]
Yes and while it's not in line with typical "snapshot" etc, I have no problem with the decision and can accommodate.
