### ISSUE TITLE
Spring Boot Documentation Update

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#136]
Spring Boot's new Maven runnable jar packages the "resources" folder contents into the path "BOOT-INF/classes" rather than the root of the jar. Because of this change the [TLS / SSL example](https://boxfuse.com/docs/payloads/springboot#tls) shown in the Spring Boot documentation no longer works with the Spring Boot 1.4.3. 

For me the properties file had to look like this:
`server.port=443`
`server.ssl.enabled=true`
`server.ssl.key-store=BOOT-INF/classes/example.jks`
`server.ssl.key-store-password=myS3cr3tPwd`

**Comment by axelfontaine** [comment]
Good catch! We have now updated this to use the new classpath: notation which was introduced in 1.3 (this was actually related to a Tomcat issue which I filed about 2 years ago).

See https://boxfuse.com/docs/payloads/springboot#tls

**Comment by forbode** [comment]
When I update will my full path still work or do I need to revert to the example in your link?

**Comment by axelfontaine** [comment]
Your full path will still work. That uses the filesystem. The example we provide uses the classpath. Both work.
