### ISSUE TITLE
Log Clarification

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#137]
I have noticed something that has been confusing. It seems as though when I run boxfuse locally (via maven in this case) it prints out a rapid set of logs then slows down to show the current apps logs. 
Question is... am I seeing old logs that are cached somewhere? The times on them are rather confusing. At the start they have old time stamps, then they catch up to current, then, after restarting numerous times due to error, they show times in the future. 

Any ideas?

**Comment by forbode** [comment]
That would be very tough. I can probably send you a sample output after changing the AWS keys. Would that help?

**Comment by axelfontaine** [comment]
Maybe it could contain a hint, yes. Feel free to sanitize it and send it by email if that's easier for you.

**Comment by forbode** [comment]
I don't see your email available anywhere. I have the file.

**Comment by axelfontaine** [comment]
This has now been fixed in Boxfuse Client 1.24.2.1223
