### ISSUE TITLE
imagemagick as native binary

### ISSUE THREAD

**Issue by csgruenebe** [boxfuse/boxfuse-issues#144]
Hi Axel,

Since this might be interessting to many other people I thought I just open a public issue on that.

Currently I am trying to get **imagemagick** running as **native binary**.

I downloaded the Unix RMPs from: https://www.imagemagick.org/script/download.php#unix
 * `ImageMagick-7.0.4-6.x86_64.rpm`
 * `ImageMagick-libs-7.0.4-6.x86_64.rpm`

and extracted them as described in the docs: https://boxfuse.com/docs/payloads/springboot#native

![image](https://cloud.githubusercontent.com/assets/9586869/22479093/cfcdab90-e7ec-11e6-9af7-41bb297b587c.png)

But it does not work with:

```
String imageMagickVersionResponse = "";
            imageMagickVersionResponse = FileCopyUtils.copyToString(new InputStreamReader(
                        new ProcessBuilder("convert", "--version").start().getInputStream(),
                        StandardCharsets.UTF_8));
```

Are these RedHat binaries not compatible? How can I build them to be compatible to the boxfuse image?

Here are the files for convenience (first unzip and then untar ..)

[native-imagemagick.tbz.zip](https://github.com/boxfuse/boxfuse-issues/files/742848/native-imagemagick.tbz.zip)

**Comment by axelfontaine** [comment]
As stated in the docs you actually have to include all shared libraries beyond the C library. You can get the list with `ldd -v`.

In the case of an RPM simply unpacking it isn't enough as this doesn't take into account the (transitive) dependencies.

An easier approach is probably to lift the binaries and libs from the latest Ubuntu/CentOS machine you have. It shouldn't take long to copy them.

**Comment by clouless** [comment]
Ok cool, that is in case of `convert`

```
ldd /usr/bin/convert
	linux-vdso.so.1 =>  (0x00007ffff31fa000)
	libMagickCore-6.Q16.so.2 => /usr/lib/x86_64-linux-gnu/libMagickCore-6.Q16.so.2 (0x00007fbde723a000)
	libMagickWand-6.Q16.so.2 => /usr/lib/x86_64-linux-gnu/libMagickWand-6.Q16.so.2 (0x00007fbde6f15000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fbde6cf7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fbde692e000)
	liblcms2.so.2 => /usr/lib/x86_64-linux-gnu/liblcms2.so.2 (0x00007fbde66d7000)
	liblqr-1.so.0 => /usr/lib/x86_64-linux-gnu/liblqr-1.so.0 (0x00007fbde64be000)
	libfftw3.so.3 => /usr/lib/x86_64-linux-gnu/libfftw3.so.3 (0x00007fbde60c0000)
	libfontconfig.so.1 => /usr/lib/x86_64-linux-gnu/libfontconfig.so.1 (0x00007fbde5e7d000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007fbde5bd2000)
	libXext.so.6 => /usr/lib/x86_64-linux-gnu/libXext.so.6 (0x00007fbde59c0000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007fbde5686000)
	libbz2.so.1.0 => /lib/x86_64-linux-gnu/libbz2.so.1.0 (0x00007fbde5475000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007fbde525b000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007fbde5051000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fbde4d47000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007fbde4b25000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fbde490f000)
	/lib64/ld-linux-x86-64.so.2 (0x000055dd86c9c000)
	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007fbde45fd000)
	libexpat.so.1 => /lib/x86_64-linux-gnu/libexpat.so.1 (0x00007fbde43d4000)
	libpng12.so.0 => /lib/x86_64-linux-gnu/libpng12.so.0 (0x00007fbde41ae000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fbde3f8c000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fbde3d88000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007fbde3b17000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007fbde3913000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007fbde370c000)
```

I will try it :)

**Comment by csgruenebe** [comment]
ok works :)
very nice!

![image](https://cloud.githubusercontent.com/assets/9586869/22487121/6483de98-e80c-11e6-8f73-dd4eac684219.png)
