### ISSUE TITLE
Timeout from AWS when rescaling an app

### ISSUE THREAD

**Issue by herder** [boxfuse/boxfuse-issues#147]
We're quite often getting errors in the Boxfuse web console when we rescale an app.
Often, it detects all but the last instance coming up when we scale up, then writes a message about timeout from AWS. All instances are up in when checking in the EC2 console, though, so the connection between AWS and Boxfuse seems to fail, I guess.

**Comment by axelfontaine** [comment]
Could you share the exact message you are getting? Also are these load-balanced or worker apps?

**Comment by jebl01** [comment]
Here is the message:
```
Configuring content-importer to scale to 6 t2.small instances in ab-prod ...
Waiting for Auto Scaling Group boxasg-abcoreboxfuse-ab-prod-content-importer-0.3.424-0 to scale to 6 Instances ...
Auto Scaling Group: i-08715fc8dc5650795 [InService]
Auto Scaling Group: i-0406b1dece4973ed0 [InService]
Auto Scaling Group: i-0b70ee361bfbd939c [InService]
Auto Scaling Group: i-04cd1e5b414e8471e [InService]
Scale failed: Time out: 2 / 6 instances failed to come up within 600 seconds => check the logs of the instances
```

This is when scaling from four to six instances, when the operation fails, the two new instances can be seen in AWS, they are healthy and receive traffic.

When trying the operation again (scaling from what BF believes are four instances to six), the operation completes within a couple of seconds... below is the log for that operation:

```
Configuring content-importer to scale to 6 t2.small instances in ab-prod ...
Waiting for Auto Scaling Group boxasg-abcoreboxfuse-ab-prod-content-importer-0.3.424-0 to scale to 6 Instances ...
Auto Scaling Group: i-0fce7ab129de72f0c [InService]
Auto Scaling Group: i-0e03dd84fa54edbb7 [InService]
Auto Scaling Group: i-08715fc8dc5650795 [InService]
Auto Scaling Group: i-0406b1dece4973ed0 [InService]
Auto Scaling Group: i-0b70ee361bfbd939c [InService]
Auto Scaling Group: i-04cd1e5b414e8471e [InService]
Successfully configured content-importer to scale to 6 t2.small instances in ab-prod.
```

**Comment by axelfontaine** [comment]
Small update: we were able to reproduce the issue and have created a fix which will go out as part of our next update. I'll let you know once it is live.

**Comment by axelfontaine** [comment]
The fix has been rolled out this morning and is now ready for you to use.
