### ISSUE TITLE
Maven plugin support user/secret decryption

### ISSUE THREAD

**Issue by binkley** [boxfuse/boxfuse-issues#148]
I'd like to use the standard maven security support for encrypted data (https://maven.apache.org/guides/mini/guide-encryption.html) to pass in my user and secret tokens to the maven plugin.

Unfortunately, this requires code in the plugin to decrypt.  Example code in the SQL mojo: https://github.com/mojohaus/sql-maven-plugin/blob/master/src/main/java/org/codehaus/mojo/sql/SqlExecMojo.java#L901.

This would let me keep my user/secret tokens in encrypted form in `settings.xml` in a server block, and refer to those as properties in my pom.

**Comment by axelfontaine** [comment]
Excellent suggestion. Yes, that makes a lot of sense!

**Comment by axelfontaine** [comment]
This has now been implemented in Boxfuse Client 1.25.2.1265
