### ISSUE TITLE
Customizable CloudWatch Logs output layout

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#153]
Currently the layout is dynamic: fields are excluded if they occurred in an exact filter and log level is indicated by color.

Proposal:
- Add a new property `logs.layout` that would default to `timestamp app? image? instance? event? 40:logger? 10:thread? account? action? user? session? request? message?` (current behavior), but could be customized to include a list of fields with an optional prefix or suffix per field for a fixed width output.
- All fields are separated by 1 whitespace.
- Fixed width output is left- or right-padded padded with additional spaces if shorter and left- or right truncated if longer.
- When `?` is added to a fieldname that field is hidden when a filter matches it exactly

Example 1: `logs.layout=level image? logger thread` shows 4 variable width fields (level, image, logger and thread) and image is hidden when `-logs.filter.image=...` is used

Example 2: `logs.layout=level:5 image logger?:30 10:thread` shows 4 fields: level (fixed width of 5, right padded or truncated if necessary), image (variable width), logger(fixed width of 30, right padded or truncated if necessary, hidden if matched exactly in filter) and thread (fixed width of 10, left padded or truncated if necessary)

**Comment by vdenisov** [comment]
I think this makes total sense

**Comment by axelfontaine** [comment]
This has now been released as part of Boxfuse Client 1.25.5.1274: https://boxfuse.com/docs/commandline/logs#logs.layout
