### ISSUE TITLE
ALB (Application Load Balancer) support

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#156]

**Comment by little-vista** [comment]
This is essential as it is now the recommended load balancer for AWS. Any word on when this is going to be supported?

**Comment by karl-ravn** [comment]
I am also curious about this. There need to be a simple way to automatically register all instances from the created autoscale-group to one or more target groups..

**Comment by axelfontaine** [comment]
Our plan is to release support for this next month. All https and http ports will be exposed by the alb and forwarded to the payload port of the instance (if not explicitly specified, https port with fallback to http port if not available). Https and http ports of the instance will only be reachable from the alb and other instances in the same asg. Non http(s) ports will be exposed according to their configured restrictions.

Comments welcome.

**Comment by ab-core-boxfuse** [comment]
Any progress yet?

**Comment by karl-ravn** [comment]
Any progress yet?

**Comment by jebl01** [comment]
Radio silence for 2 months now... what's up Boxfuse?

**Comment by axelfontaine** [comment]
@jebl01 We are currently putting the finishing touches to this. Expect it to be out either this or next week.

**Comment by axelfontaine** [comment]
This has now been released:  https://boxfuse.com/blog/load-balanced-https

Including the ability to specify custom target groups: https://boxfuse.com/docs/commandline/cfg#targetgroup
