### ISSUE TITLE
Select clocksource

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#157]
Hey,

My colleague did a performance test of our application and we think we would benefit from using ```TSC``` as clocksource as outlined in this AWS deep dive talk: https://www.slideshare.net/AmazonWebServices/cmp402-amazon-ec2-instances-deep-dive/24

Does Boxfuse use ```tsc``` as clocksource already? Do you have experiences with it or any thoughts on using it? (We don't have any experience with it, yet)

Jan

**Comment by axelfontaine** [comment]
Partly related: we have just released support for specifying Linux kernel bootloader args using a new `-linux.args=...` setting. See https://boxfuse.com/docs/commandline/fuse#linux.args

**Comment by axelfontaine** [comment]
By default, Boxfuse instances will let the Linux kernel automatically select what it thinks is the best clocksource. On EC2 this will most often be the high-resolution `xen` clocksource. You can however force the use of the `tsc` clocksource by passing `-linux.args=clocksource=tsc` when fusing an image (this is a bootloader parameter which is baked into the image and cannot be overridden later).

If all goes well the instance boot logs should then contain something along these lines:
```
11:18:02.194 [    0.091070] clocksource: xen: mask: 0xffffffffffffffff max_cycles: 0x1cd42e4dffb, max_idle_ns: 881590591483 ns
...
11:18:02.195 [    0.117504] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275000 ns
...
11:18:02.200 [    0.309031] clocksource: Switched to clocksource xen
...
11:18:02.207 [    2.080093] tsc: Refined TSC clocksource calibration: 2394.453 MHz
11:18:02.207 [    2.084003] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x2283bf4e6f2, max_idle_ns: 440795216136 ns
11:18:02.207 [    2.106077] clocksource: Override clocksource tsc is not currently HRT compatible - deferring
...
11:18:02.207 [    3.134071] clocksource: Switched to clocksource tsc
```

Please share your experiences with `tsc` so we know whether we should consider making this the default in the future.

**Comment by axelfontaine** [comment]
Here is another article on this subject which you may find interesting (and confirms that our current strategy may be the correct one): https://blog.packagecloud.io/eng/2017/03/08/system-calls-are-much-slower-on-ec2/
