### ISSUE TITLE
ERROR: Another deployment is currently in progress

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#160]
I have not been able to terminate, launch, or do anything with my app. It has been "deploying" for over 45 minutes. Hopefully, by morning it will have resolved itself. 

One thing I did do was to kill the EC2 instance, but that seems to have done nothing. 

It is my 'rest' app for my account. I am telling you now in case it persists tomorrow. I need that app back up and running asap.

**Comment by axelfontaine** [comment]
All deployments for your account seem to have completed. Please try again.

**Comment by forbode** [comment]
All is well now. For some reason though my boxfuse.io url wasn't working even though the app showed it was running. I killed the app and re-created it and it works now.
