### ISSUE TITLE
Domain based on Environment

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#169]
Is it possible to have different domains based upon the environment? 
i.e. the TEST environment might have "test-api.mydomain.com"
      The PROD environment might have "api.mydomain.com"

I am currently using Maven to configure boxfuse.

**Comment by axelfontaine** [comment]
Yes, this should work, unless you already have an existing subdomain with the same name mapped outside of Boxfuse.

**Comment by forbode** [comment]
I don't see a means to do that though? I must be missing something, but in maven you can only set one <boxfuse.domain> property.

**Comment by forbode** [comment]
I've converted to using TLS / ACM and Route 53. Great work making this easy. 

What I am really asking is this... I don't see a way to use Maven to use maven properties to have different / separate configurations for Prod vs Test. (Subnets, domain, security groups, etc). Perhaps I am not Maven savvy enough, but it isn't clear to me.

**Comment by axelfontaine** [comment]
You can achieve this by adding something like this to your `pom.xml`:

```xml
<profiles>
    <profile>
        <id>test</id>
        <activation>
            <activeByDefault>false</activeByDefault>
        </activation>
        <properties>
            <boxfuse.domain>test.myapp.com</boxfuse.domain>
            <boxfuse.subnets>subnet-12345678,subnet-12121212</boxfuse.subnets>
        </properties>
    </profile>
    <profile>
        <id>prod</id>
        <activation>
            <activeByDefault>false</activeByDefault>
        </activation>
        <properties>
            <boxfuse.domain>prod.myapp.com</boxfuse.domain>
            <boxfuse.subnets>subnet-77778888,subnet-43434343</boxfuse.subnets>
        </properties>
    </profile>
</profiles>
```

You can then select the prod profile using `mvn -Pprod` and you can find the list of property names in the second column on this page: https://boxfuse.com/docs/maven/run

**Comment by forbode** [comment]
Thank you. My apologies for not being aware of the Profiles. This worked great!

**Comment by axelfontaine** [comment]
Nothing to apologise for. Happy to help :-)
