### ISSUE TITLE
Boxfuse Console out of Synch with EC2

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#170]
This is more of a "keep an eye on it" because I cannot say exactly how I accomplished this. 

1) I was trying to get the configuration correct for deploying a Load Balanced App (which ports should be configured in my properties files)

2) In doing so I deleted the app image a few times (in order to re-upload it with minor changes rather than deploy a new image)

3) I found that some EC2 instances were running despite having ( i thought) removed them via the command line or console tool

4) I deleted them from EC2 manually as I thought they were errors

5) I noticed that the deploys / creation of an AMI was taking a long time. I checked the console and it showed that I had / have no apps deployed. However, in EC2 I do and the appropriately configured URL works

I left my console and apps in place for you to take a look.

**Comment by forbode** [comment]
In addition, this brought to my attention that the Load Balancers healthcheck endpoint will NOT be updated if you deploy once, then change your app port configuration and redeploy. This caused a timeout issue that took me a few to figure out. In itself that's an easy fix.

**Comment by axelfontaine** [comment]
The reason we don't update the ELB healthcheck config (and you get the warning in the output) is that this would cause the existing instances to start failing their healthchecks and Boxfuse tries very hard not to replace a working version by a broken one.

**Comment by forbode** [comment]
Yes, that makes sense. My test environment is fairly non critical (right now) so I didn't think of it from that perspective. 

I will be destroying my EC2 instances and ELB manually and re-running so that the console is in synch.

**Comment by forbode** [comment]
It is clear to me that if you terminate via command (CTRL-C) a deploy that it continues to run (which makes sense) and deploys. However, sometimes it does not synch with the web console (the ec2 instance is running but the console says otherwise).

**Comment by forbode** [comment]
No clear way to duplicate. Closing. 

If this happens to others I suggest deleting your EC2, ELB, etc. instances and then re-deploying your application.
