### ISSUE TITLE
Boxfuse console won't open with loading animation.

### ISSUE THREAD

**Issue by danishin** [boxfuse/boxfuse-issues#171]
This started happening after I removed hosted zone of my app in AWS while SSL is configured in boxfuse console. I'm guessing there is an internal error with regards to the above state and it won't open?

![screen shot 2017-05-17 at 3 42 43 pm](https://cloud.githubusercontent.com/assets/8480743/26141548/733ca682-3b17-11e7-9b9e-e5df1045cb78.png)

**Comment by danishin** [comment]
Also running `boxfuse destroy <APP>` fails as well.
![screen shot 2017-05-17 at 3 43 52 pm](https://cloud.githubusercontent.com/assets/8480743/26141600/b0419b46-3b17-11e7-9303-3a46597ea32c.png)

**Comment by boxfuse** [comment]
I'm unable to reproduce this now. We'll investigate what happened. Can you
try again in the meantime?

**Comment by danishin** [comment]
Yup stil the same behavior. But like I said I think this issue has to do with the current state of my app where SSL is configured with domain name `boxfuse.shiftee.io` (using AWS Route53) but I recently deleted hosted zone of `shiftee.io` from Route53. 

Perhaps your server doesn't handle case like this gracefully and thus this behavior?

**Comment by axelfontaine** [comment]
I can now confirm this is indeed what is happening. Expect a fix today. I'll keep you updated.

**Comment by axelfontaine** [comment]
We have identified the issue and completed the rollout of the fix. Everything should be back to normal.
