### ISSUE TITLE
Cannot destroy app

### ISSUE THREAD

**Issue by danishin** [boxfuse/boxfuse-issues#172]
Related: #171 

Although accessing console DOES work, destroying the app with _[misconfigured](https://github.com/boxfuse/boxfuse-issues/issues/171#issuecomment-302002075)_ ssl doesn't.

Here are some screenshots:

![screen shot 2017-05-17 at 7 40 00 pm](https://cloud.githubusercontent.com/assets/8480743/26150304/d4c6524c-3b38-11e7-91ab-105fb8025b02.png)
![screen shot 2017-05-17 at 7 40 05 pm](https://cloud.githubusercontent.com/assets/8480743/26150305/d4c8a40c-3b38-11e7-8721-320f4fa9eff0.png)

**Comment by axelfontaine** [comment]
Thanks for the report. Argh! You're right. It seems we missed this case when we reviewed this earlier today. We'll be rolling out a fix soon. Until then you can work around this by first reconfiguring your app to use the boxfuse.io domain before destroying it.

**Comment by axelfontaine** [comment]
The fix has now been rolled out and is ready for you to use.
