### ISSUE TITLE
Use custom NewRelic jar?

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#184]
I got a custom newrelic jar file from support to debug an issue we have - is there a way to use it?

**Comment by axelfontaine** [comment]
Yes, skip the regular Boxfuse support for New Relic and use it as a regular Java Agent. See https://boxfuse.com/docs/payloads/springboot#javaagents

**Comment by jtheuer** [comment]
I tried a couple of variants but without success. I must be missing a point here. I commented out the line in my config file:

```
# newrelic agent
#components.newrelic-java=3.41.0
````

and tries to run boxfuse locally:

```
> boxfuse run -env=dev
Boxfuse client v.1.29.1.1400
ERROR: Invalid NewRelic license key: SET_DURING_DEPLOYMENT => ensure it is at least 40 chars long and only contains a-f (lowercase) and 0-9
```

so I added the necessary information:
```
boxfuse run -env=dev -envvars.NEW_RELIC_LICENSE_KEY=... -newrelic.licensekey=...
```

This however /seems/ to enable the default newrelic agent:
```
vb-ea349e57 -> BOXFUSE_COMPONENTS_NEWRELIC_JAVA=3.38.0
vb-ea349e57 -> BOXFUSE_COMPONENTS_NEWRELIC_SYSMOND=2.3.0.132

**Comment by jtheuer** [comment]
Update: We've fixed our NewRelic issue already / can't confirm if this is a boxfuse issue or a problem in our config.
