### ISSUE TITLE
Temp space allocation test/prod environments

### ISSUE THREAD

**Issue by gamma-sl** [boxfuse/boxfuse-issues#186]
I need to allocate more space to /tmp so I added -tmp=10 to the run parameters. This works in the dev environment but in test and prod the volumes still appear to be 1GB rather than the expected 10GB.

**Comment by axelfontaine** [comment]
Hmm.. I can't seem to reproduce this. `boxfuse run -env=test -tmp=10` does provision a 10 GB /tmp volume for me. Can you describe the exact steps you took that triggered this?

**Comment by gamma-sl** [comment]
The only change I made was to add -tmp=10 to the run parameters. Everything else stayed the same. The last deployment was done on October 13th. Here is what AWS shows me under volumes for the instance.

Volume ID: vol-0bbce478bdd946aa5
Size: 1 GiB
Created: October 13, 2017 at 4:00:07 PM UTC-5

**Comment by axelfontaine** [comment]
Note that you should have 2 volumes attached to your instance. The root volume from the AMI (1 GB) and the /tmp volume (10 GB). Can you doublecheck this?

**Comment by gamma-sl** [comment]
That's correct, other volume is:

Volume ID : vol-0a4b10b96cd8f8d3e
Size: 1 GiB
Snapshot: snap-0f7e2b741e63fd3df
Created: October 13, 2017 at 4:00:07 PM UTC-5

**Comment by axelfontaine** [comment]
We went over this again and were able to identify the exact issue being triggered in your case. This has now been fixed and the rollout is complete. Simply retry (no need to update your client) and it should work as expected.

Sorry about the trouble,
Axel

**Comment by gamma-sl** [comment]
Confirmed. Thank you very much for fixing so quickly.
