### ISSUE TITLE
Deploy references deleted Environment with a conflict

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#189]
I created a custom environment (atlas-test-us-west-2), ended up deleting it, and now I cannot use a static IP in a new custom environment. The error message is clear, "is already in use by **** in the atlas-test-us-west-2 environment => choose a different elastic IP for this app in this environment"

This means Boxfuse' understanding of my environment is out of synch with AWS. In AWS that EIP is not associated, nor does the referenced environment exist. In this case I cannot deploy my app because I need that specific EIP.

**Comment by forbode** [comment]
FYI, I need this resolved for testing. If I don't get this resolved ASAP I cannot perform a test with an external source that is scheduled for Monday. Sorry to be a pest

**Comment by axelfontaine** [comment]
This has now been fixed. Sorry about the trouble and thanks for reporting!
