### ISSUE TITLE
JMX AWS Private Instance

### ISSUE THREAD

**Issue by little-vista-dev** [boxfuse/boxfuse-issues#195]
Hello @axelfontaine 

I have a potential memory issue with a spring app deployed with boxfuse and I wanted to set it up to accept JMX connections so that I can investigate further (from my development machine)

The instance is private (behind a load balancer) and I fuse and run it with the following params:

`-jvm.jmx -ports.jmx=1099/tcp`

Everything appears to be normal when I view the build output. At the end it prints the message:

Ready to accept JMX connections -> on each individual instance at port 1099 [user: boxfuse / password: boxfuse]

However...

I cannot connect to it using jconsole or VisualVM. I get

<img width="458" alt="screen shot 2018-01-09 at 13 13 43" src="https://user-images.githubusercontent.com/29277315/34722815-4501c6ba-f540-11e7-89c6-b4ec7a724b30.png">

I notice that in the console the -Djava.rmi.server.hostname= parameter is set to blank and this might be the reason why I cannot connect to it?

The instance does not have a public IP address but it does have a private IP address

I can ping the host on that IP address and (I can even telnet to port 1099)

The output (with some information scrubbed is)

13:05:51.095 i-xxxxxx => 2018-01-09 13:05:47.637 /jre/bin/java   -d64 -Xmx683m -XX:OnOutOfMemoryError="killall -3 java" -Djavax.net.ssl.trustStore=/cacerts/cacerts 
-Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -Djdk.reflect.allowGetCallerClass=true  **-Djava.rmi.server.hostname= -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.rmi.port=1099 -Dcom.sun.management.jmxremote.ssl=false  '**-DAWS_AVAILABILITY_ZONE=xxx-1a' '-DAWS_REGION=xxxxx' '-DBOOT_IMAGE=efi/boot/bootx64.efi' '-DBOXFUSE_ACCOUNT=xxxxx' '-DBOXFUSE_APP=xxxx' '-DBOXFUSE_COMPONENTS_BUSYBOX=1.22.1.011' '-DBOXFUSE_COMPONENTS_CACERTS=2017.02.24' '-DBOXFUSE_COMPONENTS_FREETYPE=2.6' '-DBOXFUSE_COMPONENTS_GLIBC=2.25' '-DBOXFUSE_COMPONENTS_LIBGCC=4.9.2' '-DBOXFUSE_COMPONENTS_LIBPNG=1.2.52' '-DBOXFUSE_COMPONENTS_LINUX=4.9.33' '-DBOXFUSE_COMPONENTS_OPENJDK=8.152.16' '-DBOXFUSE_COMPONENTS_TTF_BITSTREAM_VERA=1.10' '-DBOXFUSE_COMPONENTS_VBOXSF=4.9.33' '-DBOXFUSE_COMPONENTS_ZLIB=1.2.8' 
'-DBOXFUSE_INSTANCE_ID=xxxxxx' **'-DBOXFUSE_INSTANCE_IP=' '-DBOXFUSE_INSTANCE_IP_PRIVATE=10.0.10.171'** '-DBOXFUSE_JVM_JMX=true' '-DBOXFUSE_JVM_MAIN_CLASS=org.springframework.boot.loader.JarLauncher' '-DBOXFUSE_LIVE=false' '-DBOXFUSE_PAYLOAD_NAME=xxx-0.2.12-SNAPSHOT.jar' '-DBOXFUSE_PLATFORM_ID=aws' '-DBOXFUSE_PLATFORM_NAME=AWS' '-DBOXFUSE_PORTS_HTTPS=8443' '-DBOXFUSE_PORTS_JMX=1099' '-DBOXFUSE_TMP=1' '-DBOXFUSE_VERSION=1.30.3.1419' '-DHOME=/' '-DLD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/native/lib' '-DMANAGEMENT_HEALTH_DISKSPACE_PATH=/tmp' '-DNEW_RELIC_APP_NAME=xxx (xx)' '-DPATH=/sbin:/bin:/usr/bin:/native/bin' '-DPWD=/' '-DSERVER_PORT=8443' '-DSERVER_SSL_ENABLED=true' '-DSERVER_SSL_KEY_STORE=/app-config/boxfuse-selfsigned.jks' '-DSERVER_SSL_KEY_STORE_PASSWORD=boxfuse-selfsigned' '-DSHELL=/bin/sh' '-DTERM=vt102' '-DUSER=root' '-Dinitrd=initrd.gz'  -cp "/app/xxxx-0.2.12-SNAPSHOT.jar"  org.springframework.boot.loader.JarLauncher

Any ideas that will help me?

This [post](https://stackoverflow.com/questions/11628595/unable-to-remotely-connect-to-jmx) suggests that the setting the **java.rmi.server.hostname** to the IP address enables remote connection to JMX. If this is the case then where the instance has a private IP address, can boxfuse set RMI server hostname to this IP address (if the ports.jmx is configured to be universally accessible)
 
This is an urgent matter for me as I cannot recreate the performance problem running the application locally.

**Comment by axelfontaine** [comment]
@little-vista-dev Adding a fallback to the private ip if no public ip is available is indeed a good idea!

This has now been implemented in the latest client release. Update with `boxfuse -u`.

**Comment by little-vista-dev** [comment]
You are a star @axelfontaine. Thank you for the quick fix

**Comment by little-vista-dev** [comment]
@axelfontaine 
Any idea how I can download a heap dump from the instance given that there is no ssh?

**Comment by axelfontaine** [comment]
@little-vista-dev Create the heap dump under /tmp and snapshot that volume. You can then create a new volume from that snapshot and attach it to a regular EC2 instance and read the file.
