### ISSUE TITLE
Freeze on Downloading boxfuse-dev-hdd

### ISSUE THREAD

**Issue by frellan** [boxfuse/boxfuse-issues#196]
I just tried out Boxfuse, I am using the gradle plugin. When trying to do `boxfuseRun` I just get stuck on this line, every time for the last hour or so. At about 5 mins the task crashes with `Java heap size` errors. What is going on?

```
Downloading boxfuse-dev-hdd 2016.02.09 ...
```

**Comment by axelfontaine** [comment]
That artifact is actually downloaded directly from S3 onto your computer, bypassing our infrastructure entirely. What this however could be is your Gradle build not having enough memory for the verification/decompression phase. There are two easy ways to fix this: run Gradle with more heap or using the Boxfuse CLI.
