### ISSUE TITLE
ALB and custom target group

### ISSUE THREAD

**Issue by jebl01** [boxfuse/boxfuse-issues#199]
Hi!
Just noticed that it's possible to att an app to a custom target group using the CLI. How come this option isn't available in the console? Is it just a bug (since it's actually a drop down in the console - but with only the "auto create" option)?

Also, since AWS supports adding an ASG to multiple TG:s, it would be awesome if this was also possible with Boxfuse (today we rely on custom bootstrap code to add our instances to multiple TG:s...)

**Comment by jebl01** [comment]
possible only in `prod` and `test` as it seems: https://github.com/boxfuse/boxfuse-issues/issues/200

**Comment by jebl01** [comment]
Yes, but here the only alternative is the default... (auto)...
Even when set from the CLI, the chosen target group shows as "blank"...

![image](https://user-images.githubusercontent.com/431002/35912461-ee76b610-0bfc-11e8-8089-828db452b0b6.png)

**Comment by jebl01** [comment]
Also just realised that the created ASG in this scenario is created with Health Check Type EC2 and not ELB... is this a feature or bug?
Guess there might be a way to control this in the boxfuse.conf file?

**Comment by lukaswelte** [comment]
@jebl01 the ASG having EC2 instead of ELB is now fixed #215
