### ISSUE TITLE
Configuration is currently only supported on the test and prod environments

### ISSUE THREAD

**Issue by jebl01** [boxfuse/boxfuse-issues#200]
This is a bummer...
Since `prod` and `test` are totally worthless in an enterprise setup (since you cannot configure the VPC) we have never used them but created our own. This has been ok (even if the UI is cluttered with environments we don't use).

Today though, I needed to add an app to a custom target group. This is not possible from the console, so I turned to the CLI. When running the command, there is an error stating that "Configuration is currently only supported on the test and prod environments".

My suggestion:
1. Get rid of the `prod` and `test` environments. Always demand from the users that they create their own (perhaps offer a "create default environments" option when setting up your BF account?).
2. Make sure all environments are equals in Boxfuse when it comes to tooling etc.

**Comment by axelfontaine** [comment]
The wording of the error message may be incorrect here. What it should say is "Configuration is currently not supported on the dev environment".

Are you sure you specified `-env=my-custom-env` when attempting to configure?

**Comment by jebl01** [comment]
You are right... my bad :-)
