### ISSUE TITLE
Support AWS longer resource IDs

### ISSUE THREAD

**Issue by lukaswelte** [boxfuse/boxfuse-issues#201]
AWS introduced longer resource ID format which is mandatory beginning July 2018
(EC2 instances already have that long ID mandatory since December).

The new resource ID format is the resource identifier followed by 17 instead of 8 characters, e.g. for a security group old `sg-23hd918d` vs new `sg-08b8976d0fb53fd18`.

In case one of the longer resource IDs is used, boxfuse is currently throwing an error:

```
com.boxfuse.base.exception.BoxfuseException: Invalid AWS Security Group id: sg-08b8976d0fb53fd18 => ensure it matches ^sg\-[a-f0-9]{8}$
	at com.boxfuse.base.types.RegexRestrictedString.<init>(SourceFile:1019)
	at com.boxfuse.base.aws.AwsSecurityGroupId.<init>(SourceFile:18)
	at com.boxfuse.base.aws.AwsSecurityGroupId.of(SourceFile:14)
	at com.boxfuse.generator.config.BoxfuseConfig.configure(SourceFile:278)
	at com.boxfuse.client.commandline.Main.main(Main.java:89)
```

Judging based on the error message, I hope this is a quick fix by just adjusting the regex.
It would be great to support the longer resource IDs for all resources (see the following screenshot for all resources which will receive longer resource IDs)
![screenshot](https://user-images.githubusercontent.com/868286/36385193-2917f416-1592-11e8-86dc-38c2f5db0be6.png)

See the [EC2 longer resource ID FAQ](https://aws.amazon.com/ec2/faqs/#longer-ids) for more information.

**Comment by axelfontaine** [comment]
This is now available. Simply update your client and you should be good. See https://boxfuse.com/docs/releasenotes#1.32.1.1442

**Comment by lukaswelte** [comment]
@axelfontaine thanks for the super fast update!
