### ISSUE TITLE
Use custom Application Load Balancer

### ISSUE THREAD

**Issue by lukaswelte** [boxfuse/boxfuse-issues#202]
When using a Classic Elastic Load Balancer it is possible to use the `elb=` parameter of `boxfuse run` to configure using that load balancer. 
In the case the name of an Application Load Balancer is passed into `elb` boxfuse throws an error it cannot find a load balancer with that name, although an ALB with that name exists.

How should a custom ALB be configured in `boxfuse run`?

**Comment by axelfontaine** [comment]
This is what the [`targetGroup`](https://boxfuse.com/docs/commandline/run#targetgroup) parameter is for.

You can use it to tell Boxfuse to associate your app with a specific target group of a custom ALB.

**Comment by lukaswelte** [comment]
Thank you for the quick & great answer!

**Comment by lukaswelte** [comment]
@axelfontaine a quick follow up. I configured the ALB and passed the `targetGroup` parameter but I still see this error: 
```WARNING: Run failed: Unable to find ELB elevation-alpha => reconfigure elevation in alpha with a valid ELB to fix```

The ALB with that name `elevation-alpha` exists and like I mentioned `targetgroup -> elevation-alpha-target-group` was set as the parameter. Tried this with and without specifying the `elb` property, both lead to the same error.

What am I doing wrong? What is a valid ELB?

**Comment by axelfontaine** [comment]
@lukaswelte `targetGroup`works with `load-balanced-https` apps, not `load-balanced`

**Comment by lukaswelte** [comment]
@axelfontaine the type is configure as https in the conf `app.type=load-balanced-https`

**Comment by axelfontaine** [comment]
Yes, but you need to recreate the app for that change to take effect.

**Comment by lukaswelte** [comment]
Ah ok so just to be sure: I can't switch it from one commit to the other just via changing the config, instead I need to delete the app in boxfuse and add it with the new type?

**Comment by axelfontaine** [comment]
Yes, or create a new one and leave the old one as-is.

**Comment by lukaswelte** [comment]
Got it, thank you
