### ISSUE TITLE
HTTP(s) Keep Alive

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#203]
Ever since switching to the ALB I've experience slow connections, which is the result of the Connection Timeout between the ALB itself and the Target EC2 instance. 

According to the docs there are two ways to solve this. 
1) Adjust the Connection Timeout (I can up it quite a bit)
2) Set HTTP Keep alive on the server

https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout

Even if I set the Connection Timeout it seems to be slow on the initial connection (possibly 1 minute to establish). I'm hoping that if I can set Keep Alive on the Boxfuse server then the connection time will improve. 

Any ideas?

**Comment by axelfontaine** [comment]
We've not seen this issue so far. It may be worth talking to AWS support about this. Either probably not something we can fix on our end.
