### ISSUE TITLE
Hanging deploy

### ISSUE THREAD

**Issue by mbjurman** [boxfuse/boxfuse-issues#204]
Today we encountered a problem when deploying that we have never seen before. The new instances were started and put into service but the old ones still hang around. Also the boxfuse web-ui is stuck in this state
![image](https://user-images.githubusercontent.com/1282945/36838575-da208818-1d3f-11e8-883a-005fcad1f55b.png)
In AWS in Auto scaling groups we see that there was a problem starting one instance `i-013a164da3855e6ad`
```
Description:DescriptionLaunching a new EC2 instance: i-013a164da3855e6ad. Status Reason: Instance became unhealthy while waiting for instance to be in InService state. Termination Reason: Server.InternalError: Internal error on launch
--
Cause:CauseAt 2018-03-01T09:16:14Z a user request created an AutoScalingGroup changing the desired capacity from 0 to 8. At 2018-03-01T09:16:28Z an instance was started in response to a difference between desired and actual capacity, increasing the capacity from 0 to 8.
```

We are not sure what the best way is to get out of this blocked state. Can you give advice?

**Comment by axelfontaine** [comment]
Please try again. Things should be back to normal now and the next deployment should automatically clean up the dangling auto-scaling group.

**Comment by mbjurman** [comment]
Thank you for quick advice. Things look much better now.
