### ISSUE TITLE
Provision Encrypted Database (Postgres) AWS

### ISSUE THREAD

**Issue by knocknarea** [boxfuse/boxfuse-issues#206]
Is it possible for boxfuse to enable encryption for a database that it provisions on AWS?

It's only possible to do this on database creation.

**Comment by axelfontaine** [comment]
This is not yet supported, but it has a firm place on our roadmap.

**Comment by knocknarea** [comment]
@axelfontaine 

Let's say you have configured an app (spring + database) and have it happily deployed on a staging environment where you don't mind that it's a provisioned database. However, for production you want to use an encrypted database (and so need to provision and configure it yourself)

Is it possible to deploy it to production on a non-provisioned basis, i.e. db.type=none or do I have to tear it all down and start again by recreating the app with the db.type=none

BTW: this is a bit urgent for us...

**Comment by knocknarea** [comment]
@axelfontaine 
Thanks for the swift reply and advise. Luckily with boxfuse I can just tear it down and bring it back up easily enough.

When you say refer to the manually created second database, how do I do that?

**Comment by axelfontaine** [comment]
You can for example activate a different Spring profile with the alternative config.

**Comment by knocknarea** [comment]
@axelfontaine 
Very good. Thanks for your help on this. All sorted now.

**Comment by axelfontaine** [comment]
Duplicate of #143
