### ISSUE TITLE
JDK 9/10 Support?

### ISSUE THREAD

**Issue by knocknarea** [boxfuse/boxfuse-issues#210]
@axelfontaine 
Any idea when these versions will be in the inventory?

**Comment by knocknarea** [comment]
@axelfontaine Any update on this?

**Comment by axelfontaine** [comment]
Yes! Please pin the openjdk component to Java 8 for any projects you don't want upgraded. We'll release JRE 9 until 17 packages a few days after JDK 17 is released!

**Comment by knocknarea** [comment]
@axelfontaine Apologies, I don't understand what the above means? Do you have documentation on this?

**Comment by axelfontaine** [comment]
@knocknarea No worries. You simply have to add `components.openjdk=8.162.12` to your config when fusing an image. This can be done either in the config file or as part of the CLI args (ex.: `boxfuse run my-app-1.0.jar -components.openjdk=8.162.12`).

**Comment by nicoraynaud** [comment]
@axelfontaine, really looking forward to this support, do you have a more precise release date for this now that Java 17 has been released ?

**Comment by axelfontaine** [comment]
`openjdk` version `11.0.11` is now available.

Shortly after [Adoptium](https://adoptium.net/) (previously known as AdoptOpenJDK) have their first OpenJDK 17 JRE build up, we'll be publishing that to the Boxfuse Inventory as well.

Leaving this issue open until this is done.

**Comment by nicoraynaud** [comment]
Thanks, will test jdk 11 right away !

**Comment by axelfontaine** [comment]
We have now also published the OpenJDK 17.0.0 JRE based on the java.se modules of the Eclipse Temurin OpenJDK 17 distribution. This is available when using the latest Boxfuse client (1.33.7.1511).

The default OpenJDK version has now also been bumped to 11.0.11 with the latest Boxfuse client.
