### ISSUE TITLE
When using load-balanced-https the created AutoScaling groups are using Health Check Type EC2 instead of ELB

### ISSUE THREAD

**Issue by lukaswelte** [boxfuse/boxfuse-issues#215]
We are creating boxfuse application with the type `load-balanced-https` and providing a custom ALB & target group.

```
boxfuse -X run \
    -env=${boxfuseEnv} \
    -image=${image} \
    -securitygroup=${securityGroup} \
    -instanceprofile=${instanceProfile} \
    -targetgroup=${targetGroup} \
    -elb=${elbName}
```

The Target Group is configured to do health checks to determine whether applications are alive or not.
Unfortunately the AutoScaling group created by boxfuse, works great in combination with the TargetGroup, but the Health Check Type of the AutoScaling group is `EC2` and not `ELB`. Thereby instances which are not healthy in the ALB are remaining in the AutoScaling group and we can end up with no Healthy Instances in the ALB.

I looked for a boxfuse option to configure this property of the AutoScaling group, but could not find one.
Like that we can't run apps behind an ALB in production.

**Comment by axelfontaine** [comment]
Thanks for reporting and the detailed analysis. Fixed. All new deployments will now correctly use the ELB healthcheck.
