### ISSUE TITLE
Can't blue-green deploy after update: WARNING: Run failed: Unable to create auto scaling group: You must use a valid fully-formed launch template. You have requested more instances (6) than your current instance limit of 4 allows for the specified instance type.

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#216]
Hi,

I do deployments of the same application to three environments (more or less in parallel if that matters).

After my last update to `Boxfuse client v.1.33.0.1460` and switching to `r5.2xlarge` instances, I cannot blue-green deploy anymore:

```
Creating Launch Template boxlt-xx-xxx-xxx-1020 ...
Creating Auto Scaling Group boxasg-xx-xxx-xxxr-1020 ...
WARNING: Run failed: Unable to create auto scaling group: You must use a valid fully-formed launch template. You have requested more instances (6) than your current instance limit of 4 allows for the specified instance type. Please visit http://aws.amazon.com/contact-us/ec2-request to request an adjustment to this limit.
ERROR: Running xx/xxx:1020 failed!
```

My scale config says: `capacity=2-4:r5.2xlarge:cpu30-70`

And at the time of the deploy, the environments had each 2 instances running. This, maybe conincidentially, could explain the 6 instances, but why would it sum up the instances across all environments?

**Comment by jtheuer** [comment]
Ah, I think I mis-read the note and this is "only" the ec2 global instance limit and not a configuration issue from boxfuse! sorry!

**Comment by axelfontaine** [comment]
Yes, that is indeed the case. We would love to be able to handle this more specifically, but AWS only returns a generic ValidationError with an English message (not guaranteed to be stable) in the details :-/
