### ISSUE TITLE
HyperV doesnt map instance ports to localhost

### ISSUE THREAD

**Issue by J3tto** [boxfuse/boxfuse-issues#224]
When running under HyperV i'm unable to get any image to run and redirect to a localhost port. using ports or portsmap

I.e. An Image is running on 8443 but in order to access it i have to connect to the BOXFUSE_INSTANCE_IP:8443 rather than localhost:8443

Is there any way to map to localhost or pragmatically determine what the instance IP is.

**Comment by axelfontaine** [comment]
As stated in the [docs](https://boxfuse.com/docs/commandline/run#portsmap) this is for VirtualBox only. With Hyper-V your current approach is the correct one.
