### ISSUE TITLE
Increase ASG max instances from 20 to 100

### ISSUE THREAD

**Issue by emilburzo** [boxfuse/boxfuse-issues#229]
Hi,

We are trying to increase our max instances in the `capacity` config line, but we're seeing:

```
07:38:37.609 ERROR: Maximum Instance count should be between 1 and 20
com.boxfuse.base.exception.BoxfuseException: Maximum Instance count should be between 1 and 20
	at com.boxfuse.client.core.internal.console.Console.post(Console.java:351)
	at com.boxfuse.client.core.internal.console.Console.run(Console.java:648)
	at com.boxfuse.client.core.Boxfuse.run(Boxfuse.java:640)
	at com.boxfuse.client.commandline.Main.run(Main.java:325)
	at com.boxfuse.client.commandline.Main.main(Main.java:133)
```

Where is this max 20 limit coming from and how can we adjust it?

Thanks!

**Comment by jtheuer** [comment]
Hi, can you confirm that this limitation exists in boxfuse? Or is it an AWS limitation (e.g. a service limit)?
We run into this issue currently, which blocks auto-scaling for us.

**Comment by axelfontaine** [comment]
This is currently a Boxfuse limitation.

**Comment by jtheuer** [comment]
Any chance to get an increase here? It think we are going to hit that number and we rather don't want to increase the instance size (still using reserved instances). Thanks!

**Comment by axelfontaine** [comment]
This has now been rolled out. All customers can now scale their load balanced apps up to 100 instances (up from the previous limit of 20).
