### ISSUE TITLE
New RDS Certificates

### ISSUE THREAD

**Issue by knocknarea** [boxfuse/boxfuse-issues#232]
Will boxfuse support the new rds-ca-2019 RDS CA?

**Comment by axelfontaine** [comment]
The new certificates now ship with the Boxfuse client version 1.33.1.1461

Any image built with that version will be able to access RDS instances configured with the 2019 certificates.

**Comment by knocknarea** [comment]
@axelfontaine I tried this with 1.33.1.1461 and it does not appear to work. I am getting lots of these errors in my application (Java/Postgres)

"PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

I've tested this on a staging environment with the database instance using the new certificate authority.

Is there anything I am missing (configuration wise) to use the new certificate authority?
