### ISSUE TITLE
Long fusing times or fusing fails

### ISSUE THREAD

**Issue by lukaswelte** [boxfuse/boxfuse-issues#233]
We are experiencing some very long times for image fuse.
It will print: 
> Waiting for AWS to create an encrypted AMI for IMAGE_NAME in AWS_REGION (this may take up to 50 seconds) ...

but it takes way longer, sometimes even more than 15 minutes.
In addition, we experience the operation failing quite often lately.

**Comment by axelfontaine** [comment]
Thanks for the report. We have identified the issue and are working on a fix.

**Comment by axelfontaine** [comment]
Thanks for waiting. This has now been fixed.
