### ISSUE TITLE
AWS not able to create AMI

### ISSUE THREAD

**Issue by b-etf-action** [boxfuse/boxfuse-issues#237]
I have been using Boxfuse to deploy my app (PROD and TEST) without issues for well over a year, but now when trying to deploy to TEST (using the same command i've always used - boxfuse run app-name -env=test), I am getting this error.

"Running app/image failed!"
and that is it. It shows up just after "Waiting for AWS to create an encrypted AMI for app/image in us-west-2 (this may take up to 90 seconds)..." and the stack trace is

at com.boxfuse.client.core.Boxfuse.run(Boxfuse.java:653)

at com.boxfuse.client.commandline.Main.run(Main.java:325)

at com.boxfuse.client.commandline.Main.main(Main.java:133)

I am not sure where to begin in debugging this as the error message is not very descriptive and nothing has changed in my AWS account/settings or app configuration/setting etc. Any help or suggested places to start would be greatly appreciated. Thanks!

**Comment by b-etf-action** [comment]
To follow up, when I output debug log messages I see this error, so I am thinking that the AWS boxfuse AMI role is not getting/issuing the proper commands...

 Unable to read cached account data for offline use: java.lang.ClassCastException -> java.util.LinkedHashMap cannot be cast to java.util.List

**Comment by axelfontaine** [comment]
us-west-2 had its own process for creating AMIs, which was different from all other regions. We have now realigned it with the other regions and this type of failure now can't happen again.

**Comment by b-etf-action** [comment]
Ok thank you for the update, Axel. Any change you would be able to send me the policy/role for the boxfuse fast-ami role? While I was troubleshooting I made changes to this and would like to get it back to the default parameters.

Thanks!
Brian

**Comment by axelfontaine** [comment]
We have disabled fast-ami for now, so no change is necessary.

**Comment by gianlucaLigotino** [comment]
Hello, same error e same logs error now for me. Any suggestion for fix?
eu-west-1

Thanks
