### ISSUE TITLE
Cannot deploy play application with HTTPS

### ISSUE THREAD

**Issue by henricook** [boxfuse/boxfuse-issues#241]
Hi Boxfuse team,

I'm deploying a simple play application with: `boxfuse run -env=prod -domain=api.mydomain.com -app.type=load-balanced-https -tls.type=acm`. I `destroy`ed the app in Boxfuse before running this to ensure a clean slate.

We're in the Singapore AWS region, there's a verified certificate for api.mydomain.com in the ACM for this region

When the command is complete it says: `Successfully running henricook/simple-backend:0.0.0.1605434912171 in prod at http://api.mydomain.com/
`

HTTPS doesn't work though. Do you have any idea where I'm failing? I believe i've followed all the steps in the documentation

**Comment by henricook** [comment]
Fixed. When I'd first tried using `play.server.https.port=443` in my `application.conf` it wasn't working. This is because my application was an old `app.type`. After destroying the app and relaunching it as above, then adding `play.server.https.port=443` back into my `application.conf` and deploying again, all worked as expected.

**Comment by axelfontaine** [comment]
Glad to hear everything is working now. Thanks for sharing your solution.
