### ISSUE TITLE
Speed up AMI creation

### ISSUE THREAD

**Issue by henricook** [boxfuse/boxfuse-issues#242]
New customer here :wave: - It'd be really great if I could release faster to ap-southeast-1 (Singapore). 

The UI said faster releasing/deploy optimising is available for some zones, can you tell me when it might reach ap-southeast-1?

**Comment by axelfontaine** [comment]
We have now begun on-boarding customers to our new AMI creation module. Initial results indicate average AMI creations times under 30 seconds in all supported regions.

This is now the default for new users. Existing customers can get in touch to be opted-in whenever they're ready. This will be released to everyone on 2021-03-29.

**Comment by henricook** [comment]
Opted in and can confirm - this is greased lightning now. Thanks Axel!

**Comment by axelfontaine** [comment]
This has now been fully rolled out. All remaining accounts have now been moved to our new module.

**Comment by Sirioxstar** [comment]
hi,
i have the ami problem and boxfuse link this page for resolution. 
How can I solve the problem?
