### ISSUE TITLE
free plan error: t3.micro instance please!

### ISSUE THREAD

**Issue by sigi77777** [boxfuse/boxfuse-issues#253]
Hello, 
i am currently using a free plan, and t3.micro was selected during the trial phase.
I noticed only t2.micro works on the free plan, but on the dashboard i cannot switch to t2.micro on any environments (prod and test).
I understand why you guys dont want to allow bigger instances, but would it be possible for t2 and t3.micro insatnces (Which are almost the same just latter one is newer we can say) be selectable on free plan? When our business will grow, and will need more deployments and bigger instances we will for sure buy a paid plan...

Thx for considering.

**Comment by axelfontaine** [comment]
Thanks for asking. We have no plans to expand the number of instance types included in the free plan.

That being said, if you add `-capacity=1:t2.micro` to your Boxfuse CLI arguments you should be able to use a `t2.micro`. Alternatively if you wish to use other instance types like the newer t3 ones, our micro plan is only 25 USD per month.

**Comment by sigi77777** [comment]
still doesnt work...
boxfuse CLI:
ERROR: Only t2.micro instances are available on your plan, however XXXXX is currently scaled to a t3.micro instance in the test environment. Recreate the application or upgrade to a higher plan to keep using t3.micro instances.

I cannot scale it on the boxfuse web FE either:
i get the following error on prod and test settings as well: 
Only t2.micro instances are available on your plan, however XXXXX is currently scaled to a t3.micro instance in the test environment. Recreate the application or upgrade to a higher plan to keep using t3.micro instances.
