### ISSUE TITLE
Unable to configure file descriptors for tomcat application

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#254]
We tried to set the file descriptors to a higher value according to https://boxfuse.com/docs/payloads/tomcat#sysctl

Config file `src/main/webapp/WEB-INF/sysctl.conf` with the conent:

```
# double the size of the default
fs.file-max = 8192
```

However, in the charts we [plot to CloudWatch](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/package-summary.html) we still see the original value (~4096) in total:

![image](https://user-images.githubusercontent.com/96364/112137662-d2bd1e80-8bd0-11eb-8fd1-22ac543cc47c.png)

Any ideas what could go wrong here? We also had the issue with an older dropwizard stack so it might not be tomcat-specific.

**Comment by axelfontaine** [comment]
Thanks for reporting. We'll look into this and get back to you.

**Comment by jtheuer** [comment]
This might be helpful, just saw it in the log output:

```
07:42:33.276 i-09af9f04e8ec5f9ea -> i-09af9f04e8ec5f9ea => Creating 1 GB /tmp filesystem ...
07:42:33.276 i-09af9f04e8ec5f9ea -> i-09af9f04e8ec5f9ea => [    2.784036] clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x240939f1bb2, max_idle_ns: 440795263295 ns
07:42:33.276 i-09af9f04e8ec5f9ea -> i-09af9f04e8ec5f9ea => [    2.786442] clocksource: Override clocksource tsc is not currently HRT compatible - deferring
07:42:33.276 i-09af9f04e8ec5f9ea -> i-09af9f04e8ec5f9ea => Tuning kernel parameters ...
07:42:33.276 i-09af9f04e8ec5f9ea -> i-09af9f04e8ec5f9ea => sysctl: /etc/sysctl.conf: No such file or directory
```

**Comment by jtheuer** [comment]
@axelfontaine any chance for a fix here soon-ish? (New or old version)

**Comment by axelfontaine** [comment]
@jtheuer Thanks for your patience. This has now been fixed in v. 1.33.5.1506 of the client.
