### ISSUE TITLE
DB.t2.micro creation failed

### ISSUE THREAD

**Issue by sigi77777** [boxfuse/boxfuse-issues#260]
I created a new app and it fails in the first line:

02:08:01.301 Creating RDS PostgreSQL database (db.t2.micro / 5 GB / single-az) => XXXXXXXX(this one-time action may take up to 10 minutes to complete) ...
02:08:01.301 Destroying Security Group sg-XXXXXXX (XXXXXXXX) ...
02:08:02.622 WARNING: Run failed: Unable to create RDS DB instance

i am on free plan FYI.

What is going wrong?

**Comment by axelfontaine** [comment]
Some regions as well as never RDS PostgreSQL no longer support db.t2.* instance. The default has now been changed to `db.t3.micro` to compensate for this.
