### ISSUE TITLE
how to change Boxfuse default openjdk version?

### ISSUE THREAD

**Issue by metait** [boxfuse/boxfuse-issues#261]
./boxfuse inventory openjdk

returns 17.0.0.4 as the default openjdk, which does not run with our Java codes.

Is there a ./boxfuse command that i can use to change the default openjdk to lower openjdk version?

Thanks,
-ryan

Boxfuse client v.1.33.9.1515
Copyright 2021 Axel Fontaine Labs GmbH. All rights reserved.

Component Versions in the Boxfuse Inventory for openjdk:
+-----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Component | Default  |                                                                                 Other Versions                                                                                 |
+-----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| openjdk   | 17.0.0.4 | 17.0.0.3 17.0.0.2 17.0.0.1 17.0.0 11.0.13 11.0.11 8.162.12 8.152.16 8.131.11 8.121.13 8.112.16 8.102.14 8.74.02 8.60.22 8.45.14 8.40.25 8.25.18 8.20.26 7.80.32 7.65.32 7.55.14 |
+-----------+----------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
Total: 22

**Comment by axelfontaine** [comment]
Yes there is. You can add `-components.openjdk=11.0.13` for example to your command-line arguments when fusing an image to use version `11.0.13` instead. (Or replace that with `8.162.12` if you need to go back even further)
