### ISSUE TITLE
Application won't run after updating to 1.35

### ISSUE THREAD

**Issue by SLF92637** [boxfuse/boxfuse-issues#263]
I am using Boxfuse to deploy a PlayFramework application using Java 8. Since the latest update the application won't run in production. It gives the following error: 

{
    "instance": "i-09e84158f571cf790",
    "image": "slf92637/slf-kv:1.46",
    "level": "INFO",
    "message": "/jre/bin/java   -Xmx696m -XX:OnOutOfMemoryError=\"killall -3 java\" -Djavax.net.ssl.trustStore=/cacerts/cacerts -Djavax.net.ssl.trustStorePassword=changeit -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:/dev/./urandom -Djdk.reflect.allowGetCallerClass=true    '-DAWS_AVAILABILITY_ZONE=eu-central-1a' '-DAWS_REGION=eu-central-1' '-DBOOT_IMAGE=efi/boot/bootx64.efi' '-DBOXFUSE_ACCOUNT=slf92637' '-DBOXFUSE_APP=slf-kv' '-DBOXFUSE_COMPONENTS_BUSYBOX=1.22.1.012' '-DBOXFUSE_COMPONENTS_CACERTS=2020.01.14' '-DBOXFUSE_COMPONENTS_FREETYPE=2.6' '-DBOXFUSE_COMPONENTS_GLIBC=2.25' '-DBOXFUSE_COMPONENTS_LIBGCC=4.9.2' '-DBOXFUSE_COMPONENTS_LIBPNG=1.2.52' '-DBOXFUSE_COMPONENTS_LINUX=4.14.14' '-DBOXFUSE_COMPONENTS_OPENJDK=17.0.0.4' '-DBOXFUSE_COMPONENTS_TTF_BITSTREAM_VERA=1.10' '-DBOXFUSE_COMPONENTS_VBOXSF=4.14.14' '-DBOXFUSE_COMPONENTS_ZLIB=1.2.8' '-DBOXFUSE_DEBUG=false' '-DBOXFUSE_DEBUG_WAIT=false' '-DBOXFUSE_ENV=prod' '-DBOXFUSE_IMAGE_COORDINATES=slf92637/slf-kv:1.46' '-DBOXFUSE_IMAGE_ID=ba-a1b0be6311334ea09e19b8127294f212' '-DBOXFUSE_IMAGE_VERSION=1.46' '-DBOXFUSE_INSTANCE_ID=i-09e84158f571cf790' '-DBOXFUSE_INSTANCE_IP=3.122.19.7' '-DBOXFUSE_INSTANCE_IP_PRIVATE=172.31.19.88' '-DBOXFUSE_JVM_JMX=false' '-DBOXFUSE_JVM_MAIN_CLASS=play.core.server.ProdServerStart' '-DBOXFUSE_LIVE=false' '-DBOXFUSE_PAYLOAD_NAME=slf-kv-1.46.zip' '-DBOXFUSE_PLATFORM_ID=aws' '-DBOXFUSE_PLATFORM_NAME=AWS' '-DBOXFUSE_PORTS_HTTP=80' '-DBOXFUSE_TMP=1' '-DBOXFUSE_VERSION=1.35.0.1523' '-DHOME=/' '-DLD_LIBRARY_PATH=/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/native/lib' '-DNEW_RELIC_APP_NAME=slf-kv (prod)' '-DPATH=/sbin:/bin:/usr/bin:/native/bin' '-DPWD=/' '-DSHELL=/bin/sh' '-DTERM=vt102' '-DUSER=root' '-Dinitrd=initrd.gz'  -Dhttp.port=80 -cp \"/app/slf-kv-1.46/conf:/app/slf-kv-1.46/lib/*\"  play.core.server.ProdServerStart "
}

{
    "instance": "i-09e84158f571cf790",
    "image": "slf92637/slf-kv:1.46",
    "level": "ERROR",
    "message": "Oops, cannot start the server."
}

{
    "instance": "i-09e84158f571cf790",
    "image": "slf92637/slf-kv:1.46",
    "level": "ERROR",
    "message": "com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Unable to load cache item"
}

{
    "instance": "i-09e84158f571cf790",
    "image": "slf92637/slf-kv:1.46",
    "level": "ERROR",
    "message": "\tat com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2050)"
}

{
    "instance": "i-09e84158f571cf790",
    "image": "slf92637/slf-kv:1.46",
    "level": "ERROR",
    "message": "\tat com.google.common.cache.LocalCache.get(LocalCache.java:3952)"
}

I had to roll back to a previous version of boxfuse to get the application to run again.

**Comment by axelfontaine** [comment]
Boxfuse 1.35 bumped the OpenJDK default version to `17.0.0.4`. You can however easily pin the OpenJDK version to Java 11 or Java 8 instead. See https://github.com/boxfuse/boxfuse-issues/issues/261#issuecomment-961307386
