### ISSUE TITLE
"Oops, cannot start the server" error

### ISSUE THREAD

**Issue by marcus-degruttola** [boxfuse/boxfuse-issues#265]
We started seeing failures out of boxfuse when deploying an simple update yesterday.  Nothing has really changed from previous deploys so I'm a little confused with what's going on.  We run play 2.7.8 on JVM 8.

ERROR: Invalid response received from Console => try again
--
1642 |  
1643 | [Container] 2021/12/23 12:40:39 Command did not exit successfully /root/boxfuse/boxfuse run target/universal/playrestendpoints-1.0.zip -env=$BOXFUSE_ENV -ports.http=80 -ports.https=443 -capacity=$CAPACITY -instanceprofile=$INSTANCE_PROFILE -domain=$DOMAIN -envvars.DOMAIN=$DOMAIN -envvars.COGNITO_PUB_ROLE_ARN=$COGNITO_PUB_ROLE_ARN -envvars.S3_LOG_WIDGET_TABLE=$S3_LOG_WIDGET_TABLE -envvars.S3_LOG_LEARNER_TABLE=$S3_LOG_LEARNER_TABLE -envvars.S3_TRAININGSET=$S3_TRAININGSET -envvars.INGEST_FIREHOSE_NAME=$INGEST_FIREHOSE_NAME -envvars.REQUEST_TABLE=$REQUEST_TABLE -envvars.TABLE_RUBRIC=$TABLE_RUBRIC -envvars.TABLE_AUTH=$TABLE_AUTH -envvars.TABLE_SCORING_REQUEST=$TABLE_SCORING_REQUEST -envvars.TABLE_TRAINING_SESSION=$TABLE_TRAINING_SESSION -envvars.TABLE_TRAINING_SESSION_INDEX=$TABLE_TRAINING_SESSION_INDEX -envvars.TABLE_TRAINING_SESSION_SCORE=$TABLE_TRAINING_SESSION_SCORE -envvars.TABLE_TRAININGSET=$TABLE_TRAININGSET -envvars.TABLE_MODEL=$TABLE_MODEL -envvars.TABLE_METRICS=$TABLE_METRICS -envvars.TABLE_ACTION=$TABLE_ACTION -envvars.TABLE_PUBLISHER=$TABLE_PUBLISHER -envvars.TABLE_ACCESSKEYS=$TABLE_ACCESSKEYS -envvars.REQUEST_JOB_QUEUE=$REQUEST_JOB_QUEUE -envvars.REQUEST_JOB_QUEUE=$REQUEST_JOB_QUEUE -envvars.HEAD_STREAM_NAME=$HEAD_STREAM_NAME -envvars.API_SIGNAL_STREAM_NAME=$API_SIGNAL_STREAM_NAME exit status 1
1644 | [Container] 2021/12/23 12:40:39 Phase complete: BUILD State: FAILED
1645 | [Container] 2021/12/23 12:40:39 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: /root/boxfuse/boxfuse run target/universal/playrestendpoints-1.0.zip -env=$BOXFUSE_ENV -ports.http=80 -ports.https=443 -capacity=$CAPACITY -instanceprofile=$INSTANCE_PROFILE -domain=$DOMAIN -envvars.DOMAIN=$DOMAIN -envvars.COGNITO_PUB_ROLE_ARN=$COGNITO_PUB_ROLE_ARN -envvars.S3_LOG_WIDGET_TABLE=$S3_LOG_WIDGET_TABLE -envvars.S3_LOG_LEARNER_TABLE=$S3_LOG_LEARNER_TABLE -envvars.S3_TRAININGSET=$S3_TRAININGSET -envvars.INGEST_FIREHOSE_NAME=$INGEST_FIREHOSE_NAME -envvars.REQUEST_TABLE=$REQUEST_TABLE -envvars.TABLE_RUBRIC=$TABLE_RUBRIC -envvars.TABLE_AUTH=$TABLE_AUTH -envvars.TABLE_SCORING_REQUEST=$TABLE_SCORING_REQUEST -envvars.TABLE_TRAINING_SESSION=$TABLE_TRAINING_SESSION -envvars.TABLE_TRAINING_SESSION_INDEX=$TABLE_TRAINING_SESSION_INDEX -envvars.TABLE_TRAINING_SESSION_SCORE=$TABLE_TRAINING_SESSION_SCORE -envvars.TABLE_TRAININGSET=$TABLE_TRAININGSET -envvars.TABLE_MODEL=$TABLE_MODEL -envvars.TABLE_METRICS=$TABLE_METRICS -envvars.TABLE_ACTION=$TABLE_ACTION -envvars.TABLE_PUBLISHER=$TABLE_PUBLISHER -envvars.TABLE_ACCESSKEYS=$TABLE_ACCESSKEYS -envvars.REQUEST_JOB_QUEUE=$REQUEST_JOB_QUEUE -envvars.REQUEST_JOB_QUEUE=$REQUEST_JOB_QUEUE -envvars.HEAD_STREAM_NAME=$HEAD_STREAM_NAME -envvars.API_SIGNAL_STREAM_NAME=$API_SIGNAL_STREAM_NAME. Reason: exit status 1
1646 | [Container] 2021/12/23 12:40:39 Entering phase POST_BUILD
1647 | [Container] 2021/12/23 12:40:39 Running command tar --exclude=target -czf MetacogApi.tar *
1648 |  
1649 | [Container] 2021/12/23 12:40:51 Running command aws s3 cp MetacogApi.tar s3://metacogbuildfiles/backups/

{
    "instance": "i-04170f87e34a4e9f6",
    "image": "marcusdegruttola/playrestendpoints:0.0.0.1640265777322",
    "level": "ERROR",
    "message": "Oops, cannot start the server."
}

**Comment by axelfontaine** [comment]
The newest client bumped the default OpenJDK version to Java 17. If your app needs Java 8, you can force Boxfuse to use it as explained here: https://github.com/boxfuse/boxfuse-issues/issues/261#issuecomment-961307386

Did that fix your issue?

**Comment by marcus-degruttola** [comment]
Confirmed that -components.openjdk=11.0.13 solved the problem.  Thanks!
