### ISSUE TITLE
Play Framework assets not loading in new version of boxfuse

### ISSUE THREAD

**Issue by nikapolska** [boxfuse/boxfuse-issues#267]
My assets (public folder, and libs) are not loading since I've updated from Boxfuse client v.1.33.6.1510. I'm using Play Framework 2.8.8 and Scala 2.13.6. I've changed nothing in my code, old client says `you are currently offline`, new client does not load assets.

**Comment by axelfontaine** [comment]
There has been no change in how Play applications are handled on our side. However could this maybe be the cause: https://github.com/cloudcaptainsh/cloudcaptain/issues/261#issuecomment-961307386 ?

**Comment by nikapolska** [comment]
It works! Thanks!
