### ISSUE TITLE
need to know how to assign specific security group, and elastic ip to an image (ec2) instance

### ISSUE THREAD

**Issue by metait** [boxfuse/boxfuse-issues#269]
Hi,

Instead having Boxfuse to auto generate configuration for a new instance by taking all default settings, i would like to have Boxfuse to use a specific security group, and an elastic ip.

I see an option to select a security group in Boxfuse console, but i don't see an option to select an elastic IP address

Should I use command line command to configure an elastic ip? Could you let me know how i can enable elastic ip select box?

- if i create a new environment, i see elastic ip select dropdown box.
- how do i enable a current environments to take an elastic ip 

boxfuse cfg hello -env=test -securitygroup=sg-12345678 this result following error
WARNING: Configure failed: Configuration failed: Time out: Payload of Instance i-0bb920b6913db7d71 failed to come up within 300 seconds 

I have manually created a new custom security group, i see it under security group tab, but it does not come up in Boxfuse console.  Why it is not coming up in the list?

Thanks,
-ryan

**Comment by axelfontaine** [comment]
Hi Ryan,

For the elastic IP: Make sure to create your app as Single Instance (Elastic IP). The Console will then allow you to select the elastic IP.

For the custom security group: make sure it has been created in the correct region and it will appear.

Please confirm it is now working for you.

**Comment by metait** [comment]
yes, it is working
