### ISSUE TITLE
assigned a public elastic ip by Boxfuse console but, 

### ISSUE THREAD

**Issue by metagenicsit** [boxfuse/boxfuse-issues#270]
Hi,

I have assigned an elastic ip, and a custom security group.  As Boxfuse run command is executing, somehow Boxfuse assigns some other elastic ip, and other security group other than what is assigned to it either by Boxfuse console, or cfg command.  Do you have some documentation that shows how to created an EC2 instance with custom ip, and customsecurity group?

./boxfuse cfg registry-prod -env=ryan-test -securitygroup=sg-0b454xxxxxxad -elasticip=13.xx.xx.229
CloudCaptain Client (previously called Boxfuse) v.1.35.2.1525
Copyright 2022 Axel Fontaine Labs GmbH. All rights reserved.

**registry-prod already uses this configuration in ryan-test. No change necessary.**

Please refer to attached screen shot of Boxfuse configured

**### this is output from run command**
**Creating security group boxsg-xxx-ryan-test-ryan-0.0.0.1655234429761 ...** 
Instance launched in 00:32.642s -> i-037e6e160d7262682
Creating Cloud Watch Alarm for Instance auto-recovery -> i-037e6e160d7262682-auto-recovery-alarm
Waiting for AWS to boot Instance i-037e6e160d7262682 and Payload to start at **http://54.xxx.xxx.139:8761/** ...

<img width="1078" alt="Screen Shot 2022-06-14 at 11 36 22 AM" src="https://user-images.githubusercontent.com/38328948/173689164-ebd15bcd-b1a9-4587-bb61-921b974e055f.png">

**Comment by axelfontaine** [comment]
As you've no doubt seen from the rest of the logs, first the new instance is started and when it is deemed to be healthy, the elastic ip is reassigned to it. This guarantees that the elastic ip is always associated with a working instance.

Can you confirm this is working for you?
