### ISSUE TITLE
MySQL - Unable to create RDS DB instance

### ISSUE THREAD

**Issue by MSGitHub13** [boxfuse/boxfuse-issues#272]
I can't run application with MySQL on AWS:

- CloudCaptain Client v.1.35.2.1525
- App: 
  - hello (type: single-instance, tls: none, db: mysql, logs: cloudwatch-logs)
  - https://github.com/boxfuse/boxfuse-sample-java-war-hello

I am getting this error:

> 09:21:32.911 Verifying msgithub13/hello:1.0 ...
09:21:35.543 Creating security group boxsg-db-msgithub13-prod-hello ...
09:21:35.558 Authorising port 3306 ...
09:21:35.558 Creating RDS MySQL database (db.t3.micro / 5 GB / single-az) => boxdb-msgithub13-prod-hello (this one-time action may take up to 10 minutes to complete) ...
09:21:36.823 Destroying Security Group sg-0b4ff771cb62c2927 (boxsg-db-msgithub13-prod-hello) ...
09:21:36.823 WARNING: Run failed: Unable to create RDS DB instance
09:21:36.839 ERROR: Running msgithub13/hello:1.0 failed!
com.boxfuse.base.exception.BoxfuseException: Running msgithub13/hello:1.0 failed!
        at com.boxfuse.client.core.Boxfuse.run(Boxfuse.java:655)
        at com.boxfuse.client.commandline.Main.run(Main.java:325)
        at com.boxfuse.client.commandline.Main.main(Main.java:133)

Everything works fine with PostgreSQL.

**Comment by axelfontaine** [comment]
The default version for MySQL instances was still 5.6, which was no longer supported in some regions. This has now been fixed and things should once again work as expected.

**Comment by MSGitHub13** [comment]
It works fine. Thanks.
