### ISSUE TITLE
Scant JMX information JDK 17

### ISSUE THREAD

**Issue by knocknarea** [boxfuse/boxfuse-issues#274]
@axelfontaine Not sure if this is the amd64 instance or the currently latest version (available through cloudcaptain inventory)

But there is no CPU information (or GC aggregated statistics) available via JMX/JMC.

See the difference between local (JDK 17.0.4) and remote (JDK 17+35 - cloudcaptain instance on AWS)

JDK 17.0.4

<img width="313" alt="Screenshot 2022-10-21 at 09 44 15" src="https://user-images.githubusercontent.com/12442390/197155668-c6147e3d-ae8d-4bf6-924b-76f988af9055.png">

Cloudcaptain Instance
<img width="305" alt="Screenshot 2022-10-21 at 09 43 57" src="https://user-images.githubusercontent.com/12442390/197155802-d0f55669-bbeb-4571-8ac6-ab8cced6a20a.png">

It's very difficult to analyze the application in terms of tying everything to the CPU/Load, etc.

<img width="1076" alt="Screenshot 2022-10-21 at 09 54 05" src="https://user-images.githubusercontent.com/12442390/197155964-7e8d307a-252d-4556-a56f-19d9d9543f8d.png">

I wonder is it the version of JDK used by cloud captain or is it related to the AMI?

**Comment by axelfontaine** [comment]
This is most likely due to our trimmed view of `/proc` and `/sys`. We'll look at correcting this in the future. No ETA promises though.

**Comment by knocknarea** [comment]
@axelfontaine Appears to be working OK since OpenJDK 17.0.5. Thank you
