### ISSUE TITLE
Version of OpenSSL in built AMIs

### ISSUE THREAD

**Issue by igorrohal** [boxfuse/boxfuse-issues#276]
Hello,

could I ask you for a piece of information on the recently discovered OpenSSL vulnerability?
https://www.globalsign.com/en/blog/urgent-patch-openssl-november-1-avoid-critical-security-vulnerability

Are Boxfuse-built AMIs affected by this in any way? Is there any version of OpenSSL included in the micro-OS Linux kernel that is in the resulting AMI?

Thanks a lot

**Comment by axelfontaine** [comment]
@igorrohal Thanks for asking. The images don't contain OpenSSL. So not affected by this.
