### ISSUE TITLE
Failed to change CloudCaptain account while staying on same AWS infrastructure

### ISSUE THREAD

**Issue by jwallman** [boxfuse/boxfuse-issues#285]
I recently used my private account to evaluate CloudCaptain for a client on their AWS infrastructure. Upon successful evaluation, I made the necessary changes to the ExternalId in the boxfuse policy, specifying my client's account.

However, I am now encountering issues with both deleting my personal account and setting up my client's CloudCaptain account. During the AWS setup process, I receive the following warning: **"This AWS account is already being used by a different Boxfuse user."**

I kindly request assistance in removing all AWS account references associated with my GitHub account (jwallman) to resolve this issue. Your help in resolving this matter would be greatly appreciated.

**Comment by axelfontaine** [comment]
Hi Jonas, sorry for the trouble. I have now forced the disconnection of your AWS account. Please try again with your client's account. Things should now work as expected.

**Comment by jwallman** [comment]
Hi Axel! Works as a charm. Thank you!
