### ISSUE TITLE
Localization-Providers issues with `openjdk=11.0.13` caused by Flight Recorder

### ISSUE THREAD

**Issue by igorrohal** [boxfuse/boxfuse-issues#286]
Hi @axelfontaine.

We recently migrated to JRE11 and using the OpenJDK option of `components.openjdk=11.0.13` which surfaces the following OpenJDK bug in our runtime - https://bugs.openjdk.org/browse/JDK-8261913 - and makes certain parts of our localization logic broken.

The Flight Recorded became the default part of OpenJDK as per [here](https://openjdk.org/jeps/328).

We can simulate a fix locally by not running the Java Flight Recorded which became the default part of OpenJDK 11.

How can we configure the final image to remove the Flight Recorder from the runtime and thus have the Localization Providers correctly loaded?

Thanks a lot

**Comment by axelfontaine** [comment]
For OpenJDK 11 and 17 we use the x64 Eclipse Temurin (AdoptOpenJDK's successor) distribution. If you wish to customize this, you can use our [custom JRE "escape hatch"](https://cloudcaptain.sh/docs/payloads/springboot#custom-jre) and strip down the OpenJDK distribution yourself, or build your own using jlink. 

Please confirm things are now working for you again.

**Comment by igorrohal** [comment]
Hi Alex.
Thanks a lot for getting back to me. 

> For OpenJDK 11 and 17 we use the x64 Eclipse Temurin (AdoptOpenJDK's successor) distribution

I'm currently looking into the option to provide our custom Eclipse Temurin JRE within the WAR archive, as it seems that the `jdk.localedata` (https://docs.oracle.com/en/java/javase/17/docs/api/jdk.localedata/module-summary.html) is by default included in the JRE that is available in the releases [here](https://adoptium.net/en-GB/temurin/releases/).

Can it be that you're using a different and more stripped version of the JRE where you don't include the `jdk.localedata` module?

**Comment by axelfontaine** [comment]
@igorrohal I've pushed the newest JRE 11 (11.0.19) and 17 (17.0.7) versions to the Boxfuse Inventory. Their contents are unchanged from the source Temurin distributions, so hopefully this should now work for you.

**Comment by igorrohal** [comment]
@axelfontaine thanks a lot, it works all good now 🙏
