### ISSUE TITLE
Can't update to version 1.35.5.1530 due to "Download failed (unable to find valid certification path to requested target)"

### ISSUE THREAD

**Issue by SLF92637** [boxfuse/boxfuse-issues#287]
I can not update Boxfuse version to 1.35.5.1530 due to this error: Download failed (unable to find valid certification path to requested target). 

It just keeps on retrying. 

Boxfuse itself still works though.

**Comment by axelfontaine** [comment]
Hmmm what OS are you running on?

**Comment by SLF92637** [comment]
Windows 10

**Comment by SLF92637** [comment]
> Hmmm what OS are you running on?

Windows 10

**Comment by axelfontaine** [comment]
This probably means your existing client is too old. To upgrade you can also download the newest client from the CloudCaptain console.
