### ISSUE TITLE
I can't change an existing app's ELB from Classic to Application Load Balancer

### ISSUE THREAD

**Issue by tomcandysoft** [boxfuse/boxfuse-issues#289]
Even after the classic ELB was deleted manually, the next time the app is deployed, a new classic ELB is created even the argument `-app.type=load-balanced-https` is specified

**Comment by axelfontaine** [comment]
This is not supported. To migrate to an ALB, you must create a new load-balanced-https app (see https://cloudcaptain.sh/docs/apptypes). You can then deploy your existing code as part of that app, and it will be running behind an ALB instead of an ELB.
