### ISSUE TITLE
Another deployment is currently in progress for jobticket

### ISSUE THREAD

**Issue by gregjones60** [boxfuse/boxfuse-issues#291]
Hi, I was trying to deploy a new release of my Application and it appears to have died while generating the AMI as the AMI has not appeared on my EC2 console.

Are you able to check if the process has crashed somewhere?

Thanks  in advance.

**Comment by axelfontaine** [comment]
Apologies for the delay Greg. This should now be resolved. Please confirm it is now working for you.

**Comment by gregjones60** [comment]
All good now. Thanks Axel!
