### ISSUE TITLE
Help required - Unable to delete existing app in free plan

### ISSUE THREAD

**Issue by santushet** [boxfuse/boxfuse-issues#292]
Hi,
I am trying to delete app 'onlinepay' from Boxfuse but it is giving following error. Since my AWS account is locked due to some issues, I do not have access to change permissions in AWS. 

`Destroying onlinepay ...
Destroy failed: The IAM role with ARN arn:aws:iam::561921642436:role/boxfuse-user doesn't have enough permissions for Boxfuse to be able to deploy/undeploy your app => correct your IAM role policy document to allow at least the following permissions:
{"Version": "2012-10-17","Statement":[
{"Sid":"allow","Effect":"Allow","Resource":["*"],"Action":[
    "ec2:*","ebs:*","kms:*","elasticloadbalancing:*","autoscaling:*","rds:*","cloudwatch:*","logs:*","route53:*","acm:*",
    "iam:*InstanceProfile*","iam:*Role*"]},
{"Sid":"s3AllowBucket","Effect":"Allow",
    "Action":["s3:CreateBucket","s3:ListAllMyBuckets","s3:GetBucketLocation"],"Resource":["arn:aws:s3:::*"]},
{"Sid":"s3AllowObject","Effect":"Allow","Action":["s3:*"],"Resource":["arn:aws:s3:::boxfuse-*"]},
{"Sid":"ec2Deny","Effect":"Deny",
    "Action":["ec2:*"],"Resource":["*"],"Condition":{"StringEquals":{"ec2:ResourceTag/boxfuse:ignore":"true"}}},
{"Sid":"rdsDeny","Effect":"Deny",
    "Action":["rds:*"],"Resource":["*"],"Condition":{"StringEquals":{"rds:db-tag/boxfuse:ignore":"true"}}}]}`

**Comment by axelfontaine** [comment]
Unfortzunately as the credentials you provide don't have enough privileges, our platform can't do this for you either. Please check with AWS to try and fix your account issues with them. Sorry we couldn't help.
