### ISSUE TITLE
Error No payload specified  PlayFramework versión 3.0.0

### ISSUE THREAD

**Issue by vmchura** [boxfuse/boxfuse-issues#294]
Hello, I've tested PlayFramework 2.8.19, and it is working fine. However, with the new version, PlayFramework 3.0.0, it is not working anymore.

I am encountering the following error message:
```
ERROR: No payload specified and no payloads found in the current directory
=> ensure it contains at least one of these payloads types: Jar, Tomcat, TomEE, Play, Grails, JHipster, Spring Boot, Dropwizard, Node.js, Revel, Linux x64
=> alternatively specify the payload explicitly
```
I appreciate any help. Thank you.

**Comment by axelfontaine** [comment]
Thanks for reporting this. Only Play 2 is supported for now. We have no immediate plans to change this.
