### ISSUE TITLE
Progress indicator not hiding on BitBucket

### ISSUE THREAD

**Issue by dpinn** [boxfuse/boxfuse-issues#296]
This is just a question, not a bug report. For the first time, I'm using the CloudCaptain CLI in a continuous deployment environment, Atlassian Bitbucket. The logged output includes the progress indicator characters (see below).

```
Fusing Image for risk-register-cloud-3.5.0.zip (Play) ...

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/

-

\

|

/
Image fused in 00:10.866s (127134 K)
```

Is there a way to hide the progress indicator characters so that the output of my build/deployment script is more readable?

**Comment by axelfontaine** [comment]
Normally we automatically hide it in CI, but we must have missed something in our BitBucket detection. Which environment variables are present in your build? (We use those to detect a CI environment)

Alternatively you can use `-m` for machine-readable output, which will also disable the progress bar.

**Comment by dpinn** [comment]
The variables available in Bitbucket Pipelines are listed here: https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/

I'd say the CI variable is the one you want.

**Comment by axelfontaine** [comment]
Thanks David. This was a low-hanging fruit. Fixed in the latest client! (v. `1.36.1.2018`)
