### ISSUE TITLE
Support JRE 21

### ISSUE THREAD

**Issue by lychko2** [boxfuse/boxfuse-issues#303]
Hello,
We'd like to use JRE 21. I can see that by default CloudCaptain supports JRE 17. 
Does it support JRE 21 ?
If so, how do i configure it ?
If not, what's your plan ?

**Comment by axelfontaine** [comment]
JRE 21 is fully supported since client version 1.36.2 (see https://cloudcaptain.sh/docs/releasenotes#version-1362-2024-05-07)

To switch to a different JRE version follow these instructions: https://cloudcaptain.sh/docs/payloads/springboot#jre
