### ISSUE TITLE
Cloudwatch stop working after some time and not continue

### ISSUE THREAD

**Issue by dnenadovic** [boxfuse/boxfuse-issues#304]
Hello,
We are deploying Jhipster application through cloudwatch. After some time Cloudwatch logs stop writing logs from application. In that time when application is not writing in logs anymore I can write in logs with aws cli for example aws logs put-log-events --log-group-name {name_of_group} --log-stream-name {name_of_stream} --log-events timestamp=1720096628000,message=hello. I see hello in logs, but application after stoping doesn't resume to write to log files even after few days. With command boxfuse logs {instance} last message i see is "copy err exceeded buffer size limit". I suppose it is with size of logs, can i increase that size, or at least when that exception happen to make it restart cloudwatch or something like that so logs resume to work?

**Comment by axelfontaine** [comment]
The appender is open-source and can be found here: https://github.com/boxfuse/cloudwatchlogs-java-appender

Feel free to configure and/or tweak it to your needs. All config parameters are documented on its GitHub page.
