### ISSUE TITLE
boxfuse.app setting appears to be ignored (Gradle plugin)

### ISSUE THREAD

**Issue by pledbrook** [boxfuse/boxfuse-issues#31]
I have a project directory with the name _talk-submissions_, which is invalid for Boxfuse, so I added this configuration block:

    boxfuse {
        app = "talksubmissions"
        user = project.'boxfuse.user'
        secret = project.'boxfuse.secret'
    }

but when I execute the `boxfuseLs` task, I'm seeing the following error:

    * What went wrong:
    Execution failed for task ':boxfuseLs'.
    > ERROR: Invalid App name (may only contain lowercase letters and numbers): 
       talk-submissions => set boxfuse.app or boxfuse.image to a known App name to fix

**Comment by axelfontaine** [comment]
Thanks for the report. I am however having trouble reproducing this.

I have added a build.gradle to our Spring Boot sample app (https://github.com/boxfuse/boxfuse-sample-java-springboot-hello) as well to better illustrate this.

What are the exact steps necessary to reproduce this?

Thanks,
Axel

**Comment by pledbrook** [comment]
I've uploaded the project I'm having trouble with [into Dropbox](https://dl.dropboxusercontent.com/u/29802534/talk-submissions-boxfuse.zip). Just unpack it, `cd` into the _talk-submissions_ directory, and then try `./gradlew boxLs`.

**Comment by pledbrook** [comment]
If you are unable to reproduce with that project, is the `boxfuse` command line tool perhaps caching some information somewhere?

**Comment by axelfontaine** [comment]
That was very helpful. Thank you. We have found and addressed the issue. The fix should be out tomorrow with 1.8.9.

Cheers
Axel

**Comment by axelfontaine** [comment]
1.8.9 has now been released

**Comment by pledbrook** [comment]
Confirmed working, thanks.
