### ISSUE TITLE
Publish Gradle plugin to plugin repository

### ISSUE THREAD

**Issue by pledbrook** [boxfuse/boxfuse-issues#32]
Instructions for this are provided [on the plugin portal](https://plugins.gradle.org/docs/submit). This makes it easier to include the plugin in a build.

**Comment by axelfontaine** [comment]
Absolutely agree. +1

**Comment by axelfontaine** [comment]
This is currently in progress. We are hitting some limitations of the current publishing system. Discussion: https://discuss.gradle.org/t/how-can-i-publish-an-existing-plugin-jar-to-the-plugin-portal/11186/1

**Comment by axelfontaine** [comment]
No solution yet. Let's see if Gradleware can recommend something.

**Comment by pledbrook** [comment]
Agreed. From what I've read before, this isn't possible yet.

**Comment by pledbrook** [comment]
So it is possible but not ideal. In positive news, the plugin is open source and can be found [on GitHub](https://github.com/etiennestuder/gradle-plugindev-plugin). You could offer some suggestions on how you want to override the [current behaviour](https://github.com/etiennestuder/gradle-plugindev-plugin/blob/master/src/main/groovy/nu/studer/gradle/plugindev/PluginDevPlugin.groovy#L242) that sets up the publications. Note that it expects sources & docs jars.

The key question is whether you want to configure the location of the JARs via extension/convention properties or from the output of whatever task downloads/verifies/promotes the new version. The former is simpler, the latter more flexible.

**Comment by axelfontaine** [comment]
I have performed more tests (see Gradle Forum thread). The current status is still not satisfactory. Let's see if Gradleware comes up with suggestions.

**Comment by axelfontaine** [comment]
After many roundtrips with Gradleware this is now finally reality!

https://plugins.gradle.org/plugin/com.boxfuse.client

Two minor issues left (including the JavaDoc jar), but I hope Gradleware will get back to us soon so these can be resolved too.

Thank you for your support along the way!
Axel
