### ISSUE TITLE
boxfuseLs Gradle task doesn't work

### ISSUE THREAD

**Issue by pledbrook** [boxfuse/boxfuse-issues#33]
After changing the name of the project directory to _talksubmissions_ to work around #31, I once again tried the `boxfuseLs` task. Unfortunately it's not displaying anything. Just to check I also ran:

    boxfuse ls --app talksubmissions

which displayed the expected list of images.

**Comment by axelfontaine** [comment]
Thanks for the report. We had an internal debate about this at the time we implemented it. The boxfuseLs task currently logs its output as info, which is the natural level for this. Gradle however only display warnings and errors by default.

We have two options here:
- display the results as a warning
- require our users to use --info

We opted for the latter. What is your opinion about this?

**Comment by pledbrook** [comment]
Neither of those are suitable solutions. The output from the `ls` command is not logging output and should always be displayed. Hence use `System.out.println()`.

**Comment by axelfontaine** [comment]
That makes sense as it would log it as quiet. We have fixed it and it should be out with 1.8.9 tomorrow. Please use --info until then.

Cheers
Axel

**Comment by axelfontaine** [comment]
1.8.9 has now been released

**Comment by pledbrook** [comment]
Confirmed working, thanks.
