### ISSUE TITLE
Faster uploads

### ISSUE THREAD

**Issue by remiohead** [boxfuse/boxfuse-issues#38]
A big improvement in day to day use would be to support faster uploads. I have a 50Mbps up and down connection but my 200MB image takes around 45 minutes to upload.

**Comment by axelfontaine** [comment]
Hmmm upoad bypasses our infrastructure and goes straight from your machine to S3, which has enormous bandwidth available.

At 50 Mbps, you can expect roughly 5 MB/s upload, which would mean about 40 seconds in your case.

Can you try to upload the image directly to an S3 bucket of your own to compare? I strongly suspect your ISP may not be delivering the bandwidth that has been promised to you.

**Comment by remiohead** [comment]
I copied the same image directly to an S3 bucket in less than 1 minute.

**Comment by axelfontaine** [comment]
Thanks. That rules out the ISP bandwidth issue. Can you try to do the same to a bucket in eu-central-1 (where the Boxfuse Vault is located), preferably using curl instead of the S3 api? Are the times just as fast?

**Comment by axelfontaine** [comment]
Hi Shaun,

did you have the possibility to check the performance of the HTTP-based upload to S3 in eu-central-1?

Cheers
Axel

**Comment by remiohead** [comment]
Axel,

Sorry for the delay (busy times over here).

I just completed a test using curl and it took 5 minutes to complete the upload to S3. Our default region is EU-West (Ireland) but I don't see any way to specify a particular region for S3. The management console for example states that S3 does not require a region selection.

Any advice?

Shaun

**Comment by axelfontaine** [comment]
In the S3 section of the AWS console, select Create Bucket. There you can select Frankfurt as the Region. Did this work? How are the upload times there?

Could you also post a traceroute from your machine to boxfuse-vault.s3-website.eu-central-1.amazonaws.com?

Thanks,
Axel

**Comment by remiohead** [comment]
I'm not sure what happened with the other test but this one to a brand new bucket in Frankfurt took 35 seconds.

I'm using the SDK to generate a presigned URL for the upload.

Traceroute:

traceroute to boxfuse-vault.s3-website.eu-central-1.amazonaws.com (54.231.193.43), 30 hops max, 60 byte packets
 1  myrouter.home (192.168.1.1)  0.548 ms  0.653 ms  0.678 ms
 2  L100.DLLSTX-VFTTP-72.verizon-gni.net (173.71.10.1)  8.616 ms  8.472 ms  10.381 ms
 3  G0-5-3-4.DLLSTX-LCR-22.verizon-gni.net (130.81.176.196)  11.940 ms  11.859 ms  16.233 ms
 4  * * *
 5  0.ae2.XL4.DFW7.ALTER.NET (140.222.226.105)  34.435 ms  59.184 ms  44.391 ms
 6  TenGigE0-7-0-5.GW4.DFW13.ALTER.NET (152.63.101.90)  22.105 ms TenGigE0-5-0-0.GW4.DFW13.ALTER.NET (152.63.97.197)  11.487 ms TenGigE0-7-0-4.GW4.DFW13.ALTER.NET (152.63.101.86)  16.014 ms
 7  teliasonera-gw.customer.alter.net (63.65.123.46)  11.232 ms  9.588 ms  14.296 ms
 8  nyk-bb2-link.telia.net (213.155.130.208)  64.028 ms  64.650 ms  64.542 ms
 9  ffm-bb2-link.telia.net (213.155.131.150)  143.545 ms  143.479 ms  143.532 ms
10  ffm-b10-link.telia.net (62.115.137.235)  146.302 ms ffm-b10-link.telia.net (213.155.134.137)  146.526 ms ffm-b10-link.telia.net (80.91.247.189)  146.422 ms
11  a100row-ic-306996-ffm-b10.c.telia.net (62.115.46.130)  147.902 ms  147.716 ms  144.737 ms
12  * * *
13  * * *
14  54.239.5.168 (54.239.5.168)  144.705 ms  144.014 ms  143.861 ms
15  54.239.6.209 (54.239.6.209)  146.431 ms  145.103 ms  147.304 ms

**Comment by axelfontaine** [comment]
When testing with the Boxfuse Client could also please use the distribution that includes the JRE? (Just trying to rule out more causes)

**Comment by remiohead** [comment]
I edited the script to hardcode JAVA_CMD to the JRE in the boxfuse directory and to call -version:

java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

The upload speed is the same as before.

**Comment by remiohead** [comment]
I'll ask another person in a different locale to try it and let you know.

**Comment by axelfontaine** [comment]
That would be very interesting. I have to admit I am a little puzzled. We have now ruled out many possible causes leaving almost only the Boxfuse Client as a possible culprit. Yet you are literally the only one facing this issue. Many users even have 2-3 sec upload times. All the client does is a single PUT request against a pre-signed URL. Nothing exotic. Looking forward to hear what the results look like for your colleague.

**Comment by remiohead** [comment]
I remoted into our UK office and used a machine there. The upload was really fast.

Then I connected via VPN to the same network as that machine and the upload was slower than my usual speed.

I'll take it over from here Axel. The problem is clearly with my machine. I'll let you know when I figure it out.

**Comment by axelfontaine** [comment]
OK. I'll leave the issue open as I'd be very interested in learning what you find out.

**Comment by axelfontaine** [comment]
Have you made any progress on identifying the issue?

**Comment by axelfontaine** [comment]
The latest version of the client now ships with JRE 8u60. Does that improve things?

**Comment by remiohead** [comment]
Unfortunately no. The upload speed is still a small fraction of the
available bandwidth.

**Comment by axelfontaine** [comment]
We recently switched to new multipart resumable uploads. Did this improve things on your end?

**Comment by remiohead** [comment]
It's like you read my mind! I literally just seconds ago uploaded a new
image and it went significantly faster.

Much better thank you!

Shaun

**Comment by axelfontaine** [comment]
Sounds good. I'm closing this for now. Please re-open if the issue reappears.
