### ISSUE TITLE
Support auto scaling policies

### ISSUE THREAD

**Issue by remiohead** [boxfuse/boxfuse-issues#39]
I just started to experiment with load balanced projects.

It works really well but it would be even better if you could attach auto scaling policies. You can add some manually but they get lost the next time you update the build.

Our projects will get usage spikes where we have CPU utilisation triggers to bring new instances online and then reduce over time as the utilisation drops.

**Comment by axelfontaine** [comment]
We absolutely agree that Auto-scaling should be an option for Boxfuse.

Could you attach your auto-scaling policy as an example? This will help us evaluate possible ways to address this.

**Comment by remiohead** [comment]
The triggers are two CloudWatch alarms. 

The scale up alarm is breached when CPU utilisation averages 60% or above for 5 minutes. This adds 1 instance. 

The scale down alarm is breached when CPU utilisation averages 30% or below for 5 minutes. This removes 1 instance.

Unfortunately there isn't one single policy you can set to achieve this. It looks like a multi step process of creating the scaling policy in the auto scaling group and then creating the CloudWatch alarm which triggers the policy when the state moves to alarm.

**Comment by axelfontaine** [comment]
Our current thoughts on this would be to add first class support for this in Boxfuse using a syntax like this:

```boxfuse scale myapp -capacity=3-10:t2.small:cpu30-60```

This would ensure the auto scaling group always has between 3 and 10 t2.small instances that are scaled in & out according to cpu usage with thresholds set at 30% (scale in) and 60% (scale out) for 5 minutes.

Would that work for you?

**Comment by remiohead** [comment]
Sounds perfect thanks!

**Comment by dmcfarland** [comment]
A very nice addition, 
Would it also be possible to add in the time interval?
boxfuse scale myapp -capacity=3-10:t2.small:cpu30-60:5m

**Comment by axelfontaine** [comment]
We have now implemented this with support for the following syntaxes:

Format | Description
------ | -----------
5:t2.small | ensure there are always 5 t2.small instances running
2-10:m3.medium:cpu30-70 | auto-scale between 2 (min) and 10 (max) m3.medium instances, based upon average CPU load over the last 300 seconds, scale in at 30% and below, scale out at 70% and above
1-7:c4.large:cpu20-75:180 | auto-scale between 1 (min) and 7 (max) m3.medium instances, based upon average CPU load over the last 180 seconds, scale in at 20% and below, scale out at 75% and above

This is also available via the Boxfuse Console. We'll be blogging about this tomorrow.

Note: this requires updating your IAM roles permissions to the following policy include Cloud Watch:
```
{"Version": "2012-10-17","Statement":[
{"Sid":"allow","Effect":"Allow","Resource":["*"],
    "Action":["ec2:*","elasticloadbalancing:*","autoscaling:*","cloudwatch:*",
              "iam:ListInstanceProfiles","iam:PassRole"]},
{"Sid":"ec2deny","Effect":"Deny",
    "Action":["ec2:*"],"Resource":["*"],
    "Condition":{"StringEquals":{"ec2:ResourceTag/boxfuse:ignore":"true"}}}]}
```

More info: https://boxfuse.com/docs/commandline/scale.html#capacity
