### ISSUE TITLE
EC2 enhanced networking support

### ISSUE THREAD

**Issue by dmcfarland** [boxfuse/boxfuse-issues#40]
Would it be possible for boxfuse to enable enhanced networking on supported ec2 instances?
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking.html

What settings does the boxfuse OS have for file descriptors, socket reuse, max connections etc?

**Comment by axelfontaine** [comment]
This is already enabled. The kernel shipped with Boxfuse already includes the ixgbevf driver, although it is the mainline kernel tree version, not the SourceForge one.

File descriptors are sized dynamically based on the amount of RAM in the VM: http://lxr.free-electrons.com/source/fs/file_table.c#L323

Socket reuse is something you can configure in Java yourself: http://docs.oracle.com/javase/7/docs/api/java/net/StandardSocketOptions.html#SO_REUSEADDR

So are the max connections, as part of your app. You can also increase somaxconn yourself as /proc is available and everything is running as root.

Are you experiencing specific issues at this point?

**Comment by dmcfarland** [comment]
Thanks Axel,

No specific issues,  I am just evaluating Boxfuse for a new project and
wished to have a bit more information on how network connections are being
handled.

**Comment by axelfontaine** [comment]
No worries David, feel free to ask anything at any time. I'm closing this issue for now. Please reopen if you hit anything causing trouble. Fixes never take long :-)
