### ISSUE TITLE
Configurable app type per environment

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#41]
Currently when you create an an application with Boxfuse you have to specify that your app is either a single instance or load balanced.

It should be possible to set this up at an environment level instead. For example the 'test' environment would just be a single instance whereas the 'prod' environment would be load balanced.

**Comment by tomhughesnice** [comment]
Any progress on this? This would certainly mean I can remove all the load balancers in the test environment as I referenced in issue #47

**Comment by axelfontaine** [comment]
Not yet, but by judging from our discussion in #47, this may actually not be necessary anymore if that issue gets resolved. Correct?

**Comment by tomhughesnice** [comment]
Correct. I was just wondering if this was further along in development as in reality I will want different scaling rules per environment.

**Comment by axelfontaine** [comment]
We have decided not to implement this, now that #47 has (finally) been released.
