### ISSUE TITLE
Security groups not cleaned up correctly

### ISSUE THREAD

**Issue by tomhughesnice** [boxfuse/boxfuse-issues#44]
I have noticed that I have many duplicate security groups. It seems each time an application redeploys a new security group is created. Can the previous group be deleted at this time?

**Comment by axelfontaine** [comment]
Cleanup should be automatic. We'll investigate and get back to you.

**Comment by axelfontaine** [comment]
Our tests revealed that while current security groups were being cleaned correctly, old ones that for some reason hadn't been cleaned up were left there.

We have now extended the cleaning code to clean all previous security groups for a given app in the current environment.

Can you run your deployments again and confirm the security groups are now being cleaned correctly?

**Comment by axelfontaine** [comment]
I am closing this issue for now as I assume no news is good news. Feel free to reopen if necessary.
