### ISSUE TITLE
Multiple application versions deployed per environment

### ISSUE THREAD

**Issue by tomhughesnice** [boxfuse/boxfuse-issues#46]
My software follows a microservice pattern, as part of that our software is broken down into a load of separate apps that all talk to each other. 
Over time I will update each app and introduce breaking changes that will require the app connecting to it to update as well. A simple way around this would be to allow multiple software versions of the same app to be deployed. That way i will have no application downtime either.

Is this a possible update to Boxfuse in the future?

**Comment by axelfontaine** [comment]
Thank you for your suggestion.

The one thing that is unclear to us is, how would you know which version to connect to if two versions of the same app would be deployed within the same environment? Behind what kind of URL would they live? Or better said: how could you differentiate?

Would having two environments and alternating between them be a solution?

**Comment by axelfontaine** [comment]
Hi Tom,

what are your thoughts on this?

Best regards,
Axel

**Comment by axelfontaine** [comment]
Hi Tom,

did you have time to think about the two environments solution and my other questions?

Best regards,
Axel

**Comment by tomhughesnice** [comment]
My thinking was how I could canary test a new feature. But in reality I dont think I would deploy a whole extra version of a service into the stack as it just increases complexity. I think this question is redundant, I will close
