### ISSUE TITLE
Extend AWS Instance tagging to also include the standard "Name" tag

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#49]
Scope: EC2 instances

Tag name: *Name*
Tag value: *boxfuse user/app:version@env*
Example: *boxfuse myuser/myapp:1.2.3@test*

**Comment by axelfontaine** [comment]
Implemented & released.

**Comment by joosterman** [comment]
Is there a limit on the AWS name length? It might be that the user + app names take up some considerable space.

**Comment by axelfontaine** [comment]
255 characters (http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions)

We automatically truncate anything longer, but I don't expect that limit to be reached.
