### ISSUE TITLE
AWS SQS / Credentials Failing

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#52]
I can't seem to get my apps to run locally / in dev. They work fine when pushed and run in test. Why? Because I am using the Instance Profile for credentials. 

When I run inside virtual box AWS requires credentials (access and secret key). These will be retrieved through the credentials chain (Env, System, Files, or Instance profiles). I've tried setting them in Maven via both these methods:

```
<boxfuse.jvm.args>-Daws.secretKey=secretKeyVal -Daws.accessKeyId=keyVal</boxfuse.jvm.args>

<boxfuse.envvars.AWS_ACCESS_KEY_ID>accessKeyVal</boxfuse.envvars.AWS_ACCESS_KEY_ID>
<boxfuse.envvars.AWS_SECRET_ACCESS_KEY>secretKeyVal</boxfuse.envvars.AWS_SECRET_ACCESS_KEY >
```

During bootup Boxfuse shows the variables seemingly set, but AWS SDK always fails to find credentials in the chain. 
Do you see anything wrong?

**Comment by axelfontaine** [comment]
The configuration looks fine. Are you sure you are using the AWS SDK's DefaultAWSCredentialsProviderChain ? (You are using it when you don't explicitly pass in credentials to the various clients)

**Comment by forbode** [comment]
I will have a look again. I just noticed that it is possible that if I didn't change the version number Boxfuse would continually use the same local fused image rather than updating. In order to make small changes I would need to remove all local fused images, build a new jar, then re-run.

**Comment by axelfontaine** [comment]
If you use the latest client, Boxfuse will automatically re-fuse an image if the checksum of the payload changes.

**Comment by forbode** [comment]
So you are saying that if I rebuild my jar then Boxfuse will detect (via checksum) and the next time I run (maven boxfuse:run) the app it will re-fuse and then run?

**Comment by forbode** [comment]
At this point I've tried every possible way to send the credentials into the local boxfuse app. I know the app works because I can run it in Spring STS (IDE) with credentials provided as environment variables. 

I also know it works because I can deploy on an EC2 (via boxfuse) using an Instance Profile. 

What have I done locally?
1) Upgraded to the latest boxfuse
2) Killed  and removed all local images, rebuilt, then tried again. 

Any ideas?

**Comment by forbode** [comment]
The ENV vars do indeed show up in the Boxfuse print statements under ENVIRONMENT.

**Comment by axelfontaine** [comment]
If the env vars show up, then the problem most likely lies within your application. How are you creating the AWS credentials object?

**Comment by forbode** [comment]
I'm using Spring Cloud AWS with SQS. Their documentation says they use the Default Credentials Chain and it does indeed work within my IDE or via the Executable JAR (via env variables). 

I will dig into the source code for Spring Cloud AWS more to see if their is something unique I am missing.

**Comment by axelfontaine** [comment]
Hi Brad,

did you manage to resolve this? Is there anything we can do on our end?

**Comment by forbode** [comment]
I have not. I gave up as it became such a time sink that I couldn't
continue. The face that it works on the web version and in my local IDE
tells me it's not a coding issue. I have to get back to this at some point
when it becomes too important to let go.... that hasn't happened yet.

**Comment by axelfontaine** [comment]
OK, this sounds actually for a perfect case for our new debugging support: https://boxfuse.com/docs/debugging

Let me know if I can assist with anything or if there is anything we can do on our end

**Comment by axelfontaine** [comment]
@forbode Is this now working for you?

**Comment by axelfontaine** [comment]
Closing this old issue now that we automatically pass AWS CLI credentials to the VMs. Please reopen if this occurs again.

**Comment by forbode** [comment]
I still seem to have an issue here, but I believe it relates to Spring Cloud AWS. 
http://cloud.spring.io/spring-cloud-aws/spring-cloud-aws.html#_sdk_credentials_configuration

No matter what I do I cannot seem to get the Environment variables to be used by Spring Cloud AWS LOCALLY. In the cloud the credentials are passed in using instanceProfile creds. 

Again, I can confirm that during startup the AWS secret and access key are set. But I still get this:

`nested exception is com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
[INFO] vb-57b29bf7 => 2017-01-03 15:57:46.227 ui:0.7.0 vb-6f19be8f Caused by: com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain`

I'll have more info soon.

**Comment by forbode** [comment]
As we assumed it had to do with Spring Cloud AWS. There is nothing you can do about this but warn your users of the issue. The documentation isn't very clear so I had to look at the source code. Here is the issue:

**The Issue**
Spring Cloud AWS [Autoconfigure for Context Credentials](https://127.0.0.1:10443
) assumes that IF you are setting the Properties in a spring boot property file that you don't want to bother pulling credentials from elsewhere. For example:
`cloud.aws.credentials.secretKey=somerandomkey`
`cloud.aws.credentials.accessKey=somerandomkeysecret`

Using this PLUS ContextCredentialsAutoConfiguration will result in the use of a credentials chain that does not look into the Env at all. (See source code link above). This results in a failure to start the local Boxfuse app. 

So why does it work in the cloud?
Because I used `cloud.aws.credentials.instanceProfile=true` which pulls credentials from the profile.  

**Solution**
Turn off credential autoconfiguration unless you plan to put your configuration keys into your application.properties (bad idea from a security perspective). Use the @EnableAutoConfiguration in your application class to exclude it.

`@EnableAutoConfiguration(exclude = { ContextStackAutoConfiguration.class, ContextCredentialsAutoConfiguration.class })`

While I can understand this from their perspective it is annoying. I see no deploy in which it's smart to specify the access and secret key inside of the properties file. 


This issue is closed, but you can decide how to deal with communicating this in your documentation. I assume many people will use Spring Boot + Cloud AWS Autoconfigure.

**Comment by axelfontaine** [comment]
@forbode Thanks for investigating! Did you file an issue with them we could link to?

**Comment by forbode** [comment]
https://github.com/spring-cloud/spring-cloud-aws/issues/191

**Comment by forbode** [comment]
FYI, I used your logging capability to solve this issue and it has worked extremely well. In particular hooking up my IDE to the Debug port. 

Also, I have updated my issue above. I was not able to reliably turn off the Auto Configuration for Spring Cloud AWS and had to remove the import altogether. Now the application starts much, much faster and it's working locally.
