### ISSUE TITLE
Do not release Elastic IP

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#53]
Quite often when I am developing I would like to stop  or kill a currently running instance of an app. I am only looking to temporarily do this so that I can run a local copy in debug mode (I am using SQS). 

However, when I kill an app it releases the Elastic IP. Ideally I'd like to keep the same EIP so that my subdomains continue to work (via Route 53 ANAME records that point to the EIP). 

Am I missing something? Is there a way to do this?

**Comment by axelfontaine** [comment]
You can achieve what you want by using a CNAME record pointing to your boxfuse.io domain instead of the Elastic IP. Would that also work for you?

**Comment by forbode** [comment]
I'll give it a try. Clearly it would work (I didn't think of this), but what are the downsides? Does Boxfuse keep the same domain consistently? I imagine it does.

**Comment by axelfontaine** [comment]
Yes, the domain name is always consistent for the same app within the same Boxfuse environment. The only downside would be an initial additional DNS roundtrip. This is usually almost never an issue for dev.

**Comment by forbode** [comment]
This will work for me. Thanks for the back and forth.

**Comment by axelfontaine** [comment]
Sounds good. Closing for now.

**Comment by forbode** [comment]
Opening this back up... possibly. I'd really like to be in control of specifying which Elastic IP addresses to use for an instance. Ideally I could specify this in the Maven or command line "run" command. 
Why?
In my scenario I have an application I want to deploy in the future. That application needs an IP address NOW, not when I deploy it. That IP address will be given to an external customer so they can configure their firewalls, etc... I am not ready to deploy the application right now, but need that IP. 

I suppose the only other solution is to deploy the app even though it's not done, get the IP, and then kill the running app. Will that save the Elastic IP even though I don't have the app running? 

I don't want to run an app for months just because I need an elastic IP.

**Comment by forbode** [comment]
So that I can work around this...
When is the elastic IP released? When I remove a deployed production or test app? Or when I delete the entire application in boxfuse? 

Basically the more I understand about when I lose the EIP the easier I can work around it.

**Comment by axelfontaine** [comment]
Currently an EIP is released when the application is killed ("boxfuse kill") within an environment.

**Comment by forbode** [comment]
Ok, so there is really no way around having to run an application to hang onto an EIP, right?

**Comment by axelfontaine** [comment]
This is now possible both via the Console and the Boxfuse Client. See https://boxfuse.com/docs/commandline/cfg#elasticip
