### ISSUE TITLE
SSL with Spring Boot

### ISSUE THREAD

**Issue by forbode** [boxfuse/boxfuse-issues#54]
I've followed the online Spring Boot deployment for standard HTTP and everything is working fine. The app starts, tomcat provides port 80 access, etc...

However, if I attempt to make the application use SSL it fails to start within AWS (Fails the health check). Here are the details:

Using this configuration in the application-boxfuse.properties (replacing with my jks and password):
```
server.port=443
server.ssl.enabled=true
server.ssl.key-store=example.jks
server.ssl.key-store-password=myS3cr3tPwd
```

Yes, the JKS ends up in the root of the jar. 

I am using a SELF SIGNED certificate for now so I thought that was the issue, but I turned off health checks and it didn't help. The server never responds. 

Because this works without the above config and because I do in fact see, in the logs, that the server started, I am posting this as a potential bug for feeback. Here is the log snippet:

```
Wed 16:58:33 01-20-16 INFO [main] com.atlasground.RestApplication - Started RestApplication in 53.746 seconds (JVM running for 54.429)
```

**Comment by forbode** [comment]
I should also add that I can setup SSL locally, within my IDE, with the very same settings. I know the keystore works in other words.

**Comment by axelfontaine** [comment]
Are you sure your security group configuration is correct? Are you using a Boxfuse auto-generated security group or your own? If you use your own, make sure port 443 is open to the world, so Boxfuse can cleanly healthcheck your application.

**Comment by forbode** [comment]
Well I must admit that I feel dumb for having wasted so much time. There are so many moving parts I forgot to check my custom security group. Yes, my security group was not setup for SSL. 

You should leave this here for others to take note.

**Comment by axelfontaine** [comment]
This is of course something Boxfuse would have taken care of automatically, should it have generated the security group for you. If you don't mind me asking, what is the reason you need a custom security group?

**Comment by forbode** [comment]
I have at least 5 different servers with each running a different application. However, they all typically require the same ports open or closed. It is much easier if I assigned the same security group to all of them and can update them all at once vs boxfuse auto creation (which creates one per app).

**Comment by axelfontaine** [comment]
Fair enough. Thanks for sharing.
