### ISSUE TITLE
Limit subnets within a VPC

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#56]
I would like to have the possibility to define the vpc/subnet configuration of my aws environment with the commandline client. Would be also important to make sure the correct AZs are used.

**Comment by axelfontaine** [comment]
Just so I understand you correctly: you have existing non-default VPCs that you would like to use with Boxfuse and inside those VPCs you would like to make use of some, but not all subnets. Is this correct?

**Comment by jtheuer** [comment]
Yes, thats is my setup. Don't get me wrong, I like the current convention-over-configuration approach a lot, but sadly I need a little bit of configuration here...

**Comment by axelfontaine** [comment]
I didn't get you wrong, just trying to get a better idea to make sure I fully understand your needs :-)

What is the reason you want to use some, but not all the subnets in a VPC? What does your specific scenario look like?

**Comment by jtheuer** [comment]
First, our account does not have a default VPC because the account is from the pre-VPC era. I'm not sure if the first VPC I created had it but since i deleted it after the first try there is no way to get a "default" vpc back, anyway, according to the docs.

Second, autoscaling & reserved instances: From my understanding it is not possible to launch an elb+as setup, allow all three subnets but force the placements of the first instances into subnet-a and subnet-b. This would be important if I purchase RIs. Correct me If my knowledge isn't up-to-date here.

Third, permission isolation: I would like evaluate if it is possible to restrict access of boxfuse to one VPC.

Not-yet-relevant for me: Since amazon recently launched the managed NAT we would like to add private subnets and not only use public subnets, so in the (far) future we'd like to have the instances in private subnets and the ELB in public. (This one of their recommendations for larger VPCs) This is NOT part of this issue.

Hope this makes our use-case clear.

**Comment by axelfontaine** [comment]
Default VPC: You can ask AWS support to (re-)create it for you. It is pretty simple and it is usually done within a couple of hours.

ASG & RI: I certainly understand the need to restrict the subnets (and therefore AZs) to get the benefits of the RIs. However what I don't understand here is: why do you want to have 3 subnets available to your ELB if you will only ever allow your ASG to launch instances in two of them?

One VPC: this is effectively the case now with the default VPC, however I certainly get the need to support this for other VPCs as well.

I feel we really have two issues here:

- Support for non-default VPCs
- Limit subnets within a VPC

## Non-default VPC support
I have filed a new issue for non-default VPC support (regardless of the application type): https://github.com/boxfuse/boxfuse-issues/issues/57

Please review the proposed syntax and let us know if it would work for you.

## Limit subnets within a VPC
Let's keep this issue for limitings subnets within a VPC.

Here is my proposal:

- Deprecate the `-subnet=...` parameter
- Introduce a new `-subnets=...` parameter that accepts a comma-separated list of subnet IDs (which must all be within the VPC specified in #57)

Syntax proposal: `boxfuse cfg -env=test -vpc=vpc-12345678 -subnets=subnet-aaaa1111,subnet-bbbb2222`

Would this work for you?

**Comment by jtheuer** [comment]
About the ```-subnets```parameter: Looks fine!
And of course ELB & application should use the same subnets (That was one of your questions above). It doesn't make sense to have different configurations here (unless you built a complex vpc with private and public subnets - that is on another page).

**Comment by herder** [comment]
Just chiming in here, waiting eagerly for this feature... :)

Since we can already specify which ELB to use, we could create an ELB with its own subnets, and then configure the app's subnets through this parameter.
Also, in the future it would be nice to have an `-elb-subnets=aaa111,bbb222` parameter to be able to specify this from Boxfuse.

**Comment by axelfontaine** [comment]
@herder Coming very soon!

An `elb-subnets` parameter would probably not be necessary, as you will either fully manage the ELB yourself or let Boxfuse create it with the subnets from the `-subnets` parameter. Does that make sense?

**Comment by axelfontaine** [comment]
We have just released support for this feature. It is available both from the Boxfuse Client and the Boxfuse Console.

You can now specify the list of subnets you want (max 1 per az as per AWS limitations). Boxfuse will then use that list when creating ELBs and ASGs.

**Comment by herder** [comment]
Looks great! A small improvement request: would it be possible to also display the name of the subnet, if present?

**Comment by axelfontaine** [comment]
@herder Done :-) The name tag is now displayed next to the subnet id on the config screen if available.

**Comment by herder** [comment]
Awesome, thanks! 👍
