### ISSUE TITLE
Support non-default VPCs

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#57]
Allow the VPC to be selected per environment.

Proposed syntax: `boxfuse cfg -env=test -vpc=vpc-12345678`

A change of VPC would only be possible when there are currently no apps deployed within that environment.

- [x] Creating custom environments with a non-default VPC
- [ ] ~~Allow setting Boxfuse region to one that doesn't have a default VPC~~ <br>
  (We opted for a good error message with a link to the relevant AWS Knowledge Center page instead)
- [ ] Allow configuring existing environments via the Boxfuse Console
- [ ] Allow configuring existing environments via the Boxfuse Client

**Comment by axelfontaine** [comment]
@jtheuer Would this work for you?

**Comment by jtheuer** [comment]
That looks great, thanks!

**Comment by axelfontaine** [comment]
Starting today you can now deploy to non-default VPCs by setting the VPC when creating custom environments. ELBs created in those environments currently use all of the VPC's subnets.

Support for creating custom environment from the Boxfuse Client will follow in the near future.

**Comment by axelfontaine** [comment]
Moved the two open points to #80 and #81 and closing this one as it is effectively implemented.
