### ISSUE TITLE
Make it possible to specify environment variables when launching instances from the Console

### ISSUE THREAD

**Issue by axelfontaine** [boxfuse/boxfuse-issues#58]

**Comment by sudarshan89** [comment]
This will also enable setting the spring profile value. A issue that I am facing is that each time I deploy from the console it starts to use the default spring profile rather than the env (dev,prod,test) specific one.

**Comment by lizell** [comment]
Is there any reason that the environment variables are not fused in the image? It would make a lot of sense to be able to set up a basic set of environment variables with license keys, etc. and then being able to override them via the Console or CLI.

As it is now, if I re-run an image from the CLI or choose to run a specific version in prod I loose all the environment variables that were available in the stage version (built from a CI or similar).

**Comment by axelfontaine** [comment]
@lizell That would actually be consistent with most other settings which can also be added/overridden. I have opened #89 for this.

**Comment by axelfontaine** [comment]
This is now supported.
