### ISSUE TITLE
IAM Instance Profile

### ISSUE THREAD

**Issue by sbezkostnyi** [boxfuse/boxfuse-issues#59]
There is an option in Boxfuse Console to assign instance profile for specific environment, but looks like it doesn't work.

I've created role, that allows EC2 instance access to S3 and selected it in Boxfuse Console, but after application reconfiguration I see that instance profile not assigned to EC2 instance.

I've tried to fully kill and re-deploy app, but it still doesn't work.

**Comment by axelfontaine** [comment]
Hi Sergey,

We tried to reproduce this, but couldn't get it to fail. What exactly do you mean with " looks like it doesn't work"? Are you able to see the IAM role in the EC2 part of the AWS Console (select your instance and look towards the bottom right where it says "IAM role")?

Best regards,
Axel

**Comment by sbezkostnyi** [comment]
No, instance does not have IAM role.

**Comment by axelfontaine** [comment]
Thanks for checking.

OK and does it show the IAM instance as being configured in the Boxfuse Console? If yes, could you give us the exact steps on how to reproduce this?

**Comment by sbezkostnyi** [comment]
Yes, Boxfuse console shows IAM instance profile selected.

My application is Spring Boot application. And I'm using Boxfuse Maven Plugin.
In Boxfuse console I've created Load Balanced with Zero Downtime updates with MySQL database application.

I tried to remove app and create new one, my steps:

1. stopped running application with `mvn boxfuse:kill`
2. removed all database backups from AWS
3. removed all images from Vault
4. removed application from Boxfuse console
5. created new application in Boxfuse console (Load Balanced with Zero Downtime updates with MySQL database)
6. configured IAM instance profile for application
7. built and deployed application with `mvn clean package boxfuse:fuse boxfuse:run`

Newly started EC2 instance does not have associated IAM role.

Environment:

- Java Oracle JDK 1.8.0u74
- Maven 3.3.9
- Boxfuse Maven Plugin 1.17.8.903

**Comment by sbezkostnyi** [comment]
After a couple of tries I found that it works well if I use "Single Instance with Zero Downtime updates" application type instead of "Load Balanced with Zero Downtime updates" application type.

**Comment by axelfontaine** [comment]
Thank you for providing the reproduction steps and isolating the issue. That was incredibly helpful.

We have identified and fixed the issue. We have completed the roll out of the update and everything is ready for you to use.

Please confirm it is working as expected now.

Thanks!

**Comment by axelfontaine** [comment]
Hi Sergey,

can you confirm this is now working for you?

Thanks,
Axel
