### ISSUE TITLE
set environment variable

### ISSUE THREAD

**Issue by altfatterz** [boxfuse/boxfuse-issues#63]
I am trying to set an environment variable using the `-envvars` but it does not seem to work. 
```
boxfuse run -envvars.foo=bar
```
but in the Spring Boot Actuator `/env` does not show up as an environment variable.

What am I doing wrong?

**Comment by axelfontaine** [comment]
What do they instance boot logs say? Also can you access it programmatically using System.getenv()?

**Comment by altfatterz** [comment]
my mistake, not expose somehow to actuator endpoint, but it is set. 
thanks Axel.
