### ISSUE TITLE
configure load balancer created by boxfuse to listen on port 80

### ISSUE THREAD

**Issue by altfatterz** [boxfuse/boxfuse-issues#65]
I was wondering if I can configure the automatically created load balancer to listen on port 80 and forward to instance port 8080. 

I was trying with a spring boot app creating a test profile `application-test.properties`

```
server.port=80
```

```
boxfuse run chucknorrisfacts:1.0 -env=test '-envvars.SPRING_PROFILES_ACTIVE=$BOXFUSE_ENV'
```

but still the automatically created load balancer is listening on 8080. 

What am I doing wrong?

**Comment by axelfontaine** [comment]
The devil is in the details.

To quote the documentation (https://boxfuse.com/docs/payloads/springboot#configuration):

> Boxfuse parses application-boxfuse.properties and automatically configures the ports and the healthcheck based on the information it contains.

> If no application-boxfuse.properties is found at the root of the jar file, Boxfuse will automatically look for application-default.properties and application.properties. The overriding order matches the default Spring Boot one.

This basically means you have two options:

1. Put `server.port=80` in either `application-boxfuse.properties`, `application.properties` or `application.properties` and Boxfuse will automatically detect the correct value and set things up as you would expect
2. Pass the port value explicitly. Ex.:
`boxfuse run chucknorrisfacts:1.0 -env=test '-envvars.SPRING_PROFILES_ACTIVE=$BOXFUSE_ENV' -ports.http=80`

Can you confirm this is now working for you?

**Comment by altfatterz** [comment]
Unfortunately it doesn't work.

In my example I using a different Spring profile for each boxfuse environment

`application-test.properties` contains the `server.port=80` and I am enabling the `test` profile with 

```
boxfuse run chucknorrisfacts:1.0 -env=test '-envvars.SPRING_PROFILES_ACTIVE=$BOXFUSE_ENV'
```

**Comment by axelfontaine** [comment]
I just checked the logs for your account and saw the following warning:

`ELB (boxlb-altfatterz-test-chucknorri) healthcheck is currently configured as HTTP:8080/health but should be HTTP:80/health for altfatterz/chucknorrisfacts:2.0 => adjust in the AWS console to fix`

This means the ELB was created at the time the application was configured to run on port 8080.

You have to options to fix this:

1. Manually update your ELB in the AWS Console to use port 80 instead of 8080
2. Kill the application in that environment and re-deploy it. Boxfuse will then automatically create a new ELB with the correct ports

**Comment by altfatterz** [comment]
I have created a simple example describing the confusion when using custom Spring profiles (instead of the default boxfuse profile)

https://github.com/altfatterz/boxfuse-hello-world

**Comment by axelfontaine** [comment]
Auto-configuration for multiple environments is something we have considered in the past (https://github.com/boxfuse/boxfuse-issues/issues/30).

However with Spring Boot it is nearly impossible to get 100% right as you can still set your environment on application startup (in an ApplicationContextInitializer), which can also override whatever environment variables you have set.

In your case, the best option is probably to use a dummy `application-boxfuse.properties`file containing the port setting or passing it in manually with `-ports.http=80` which will then automatically configure Spring Boot to use port 80. On VirtualBox you can then use `-portsmap.http=8081` to map the VM's 80 port to your host's 8081 port.

Would this do the job for you?

**Comment by altfatterz** [comment]
Yes, it will work for now. Thanks Axel! Just maybe we can note in the docs that the `server.port` in custom Spring profiles will not work.

**Comment by axelfontaine** [comment]
You are welcome and thanks for the hint about the docs! We have just amended them to make the relationship between profiles and configuration clearer.
