### ISSUE TITLE
not authorized when trying to deregister an ami created by boxfuse

### ISSUE THREAD

**Issue by altfatterz** [boxfuse/boxfuse-issues#66]
I am wondering how could I deregister some left over private ami's created by boxfuse.

The above happens with an IAM user (AdministratorAccess permission) or with the root account. 

```
aws ec2 deregister-image --image-id ami-7466801b

A client error (AuthFailure) occurred when calling the DeregisterImage operation: Not authorized for image:ami-7466801b
```

Normally when I `boxfuse destroy` the application the ami is deregistered successfully. Is there other way to clean up the ami's created by boxfuse? Am I missing a permission?

Thank you.

**Comment by axelfontaine** [comment]
`boxfuse rm myapp:123 -vault` is your friend here (https://boxfuse.com/docs/commandline/rm)

This will remove an image from the Vault as well as its matching AMIs.

Does that do the job for you?

**Comment by altfatterz** [comment]
great, thank you. The docs on the `rm` does not mention it though that the matching AMIs are also deleted.

**Comment by axelfontaine** [comment]
Good point. We have just updated the docs to make this clearer. Thanks!
