### ISSUE TITLE
application and environment naming, version detection?

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#67]
What is the convention for the application naming and version detection? I currently produce two artifacts with my maven build, the default jar and a fat jar: 

```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>2.2</version>
            <configuration>
                <outputFile>${project.build.directory}/${project.artifactId}-${project.version}.fat.jar</outputFile>
```

[...]

Boxfuse detects the correct fat jar, but doesn't name it as I would like (Project artifact id)

```
WARNING: Invalid Image version (may only contain numbers and dots): 0-SNAPSHOT.fat => use image to set, falling back to auto-generated version for now: 0.0.0.1459860621654
Fusing Image for snufkin-0-SNAPSHOT.fat.jar ...
```

I don't really care about the version because it is "0-SNAPSHOT" for dev builds always and for live builds I want to use the jenkins build number since we use that for the github tags, too.

How should I name my final artifact?

Jan

**Comment by axelfontaine** [comment]
Boxfuse looks for the following naming pattern:

_appname_-_version_._extension_

In your case you should then either change the output file to
`${project.build.directory}/${project.artifactId}-fat-${project.version}.jar`

(This would however by default change your app name to `snufkin-fat`)

Another alternative is to set the app name explicitly by setting the `boxfuse.app` property which will override what has been auto-detected.

**Comment by jtheuer** [comment]
That works, I found the ```app``` property for the app name.

Is there a documentation of all available configuration options? I found some in the global boxfuse.conf and guessed some from the commandline properties. What I still need is the version property (and it doesn't look like it is ```version```)

Jan

**Comment by axelfontaine** [comment]
Hi Jan,

You can use `boxfuse.image` for this when fusing to specify both app name and version. We'll be amending our docs to make this clearer.

**Comment by axelfontaine** [comment]
Closing old issue
