### ISSUE TITLE
Also apply boxfuse.conf settings for boxfuse cfg and boxfuse scale directly with boxfuse run

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#74]
I like to have all Infrastructure configuration as code so I put my environment settings into a ```boxfuse.conf``` in my project:

```
app=myapp
version=0
envvars.NEW_RELIC_APP_NAME=mayapp-$BOXFUSE_ENV
securitygroup=sg-9e47a7f9
instanceprofile=routing-vpc-DefaultInstanceProfile-HY01TGQK6VBP
elb=myapp-production
capacity=2-10:t2.small:cpu30-70
```

When I initiate a bluegreen deployment with ```boxfuse run -env=production -configfile=boxfuse.conf```, the new launch config still contains the old settings.
Do I misunderstand the role of the boxfuse.conf or is it just a bug? Would other settings be updated, or none of them?

**Comment by axelfontaine** [comment]
Currently you would have to invoke

```
boxfuse scale -env=production -configfile=boxfuse.conf
boxfuse run -env=production -configfile=boxfuse.conf
```

to achieve what you want.

I certainly agree however that being to adjust the settings normally provided via the `cfg` and `scale` commands as part of the invocation of the `run` command would definitely make sense.

**Comment by axelfontaine** [comment]
As of 1.19.7.987 you can now specify the `capacity` directly with `boxfuse run` (`boxfuse scale` functionality). See https://boxfuse.com/docs/commandline/run#capacity

**Comment by axelfontaine** [comment]
As of 1.19.8.990 all the functionionality of `boxfuse scale` and `boxfuse cfg` is now available directly from `boxfuse run`
