### ISSUE TITLE
Option to lock the web ui

### ISSUE THREAD

**Issue by herder** [boxfuse/boxfuse-issues#82]
I'm a little nervous about the power of the web UI - for example, a complete destruction of an environment is just a few clicks away.

Would it be possible to add an option in the CLI to lock/unlock the web console, and configure stuff only through the CLI when the web console is locked?

Even better would be to be able to tie users to the main account as admin/developer, like for example Heroku, but that's probably a bigger issue... :)

**Comment by axelfontaine** [comment]
Hmm as we strive to achieve parity between the Client and the Console locking down only the Console is not something that I see as being able to provide tangible benefits. (For now you can achieve this by only sharing the GitHub account credentials with the "admins" and letting the "developers" only use the Boxfuse Client with the associated user and secret)

However, the role support with different permissions (admin/developer/readonly) is certainly a direction we want to move into. I have updated #43 to include this.

Does this sound reasonable to you or did I miss something?

**Comment by herder** [comment]
Yes, the role support is what I see as the better long-term solution, so if that is where you're going I'm happy :)

**Comment by axelfontaine** [comment]
Sounds good. Closing this one in favor of #43
