### ISSUE TITLE
Options to specify VirtualBox networking

### ISSUE THREAD

**Issue by anders-holmberg-baath** [boxfuse/boxfuse-issues#84]
It would be awesome if there were some options to customize the VirtualBox network adapter setup. Currently each guest is configured with an adapter set to `NAT` which prevents multiple guests to communicate with each other.
I would like to be able to setup a `Host-only adapter` instead of the default `NAT`, so that each guest can enter the same virtual network, as well as be accessible from the host running the guests. This way, I could add a custom guest running with one adapter in the `Host-only` network and another adapter with access to the host-network exposing DHCP and DNS services to the `Host-only` network and act as a gateway for outbound traffic.
This would allow setting up a "standard" Netflix stack locally, running a Eureka instance (boxfuse instance) and a set of Eureka enabled boxfuse instances primarily communicating with each other, but with the occasional need for external access.

Proposed options (`cfg`) *VirtualBox only*:
`-adapter=NAT/Host-only` (including perhaps any other option exposed by VirtualBox that makes sense)
`-networkname=<name>` (makes sense only for `Host-only`, if NAT and Host-only are the only options for `-adapter`, but can be used with some of the other adapter alternatives VirtualBox exposes. Potentially the `-subnets` option for AWS deployment could be reused, but it could also introduce undesired ambiguity. I leave it up to someone with better judgement to decide on that.

**Comment by axelfontaine** [comment]
This is not necessary. You can already accomplish this today with NAT networking. If you have service a and service B each running in a guest on the same host and service a exposes port 1234, service B can access it at either 10.0.2.2:1234 or $BOXFUSE_HOST_IP:1234

Would this do the job for you?

**Comment by anders-holmberg-baath** [comment]
My expertise in regard to VirtualBox is limited, so it may very well be a case of PEBCAK 😄.
However, using the current setup, each guest will have the same IP, assigned by VirtualBox in the 10.0.2.0 address space. This, however, conflicts with the network I have my workstation on, so the routing to the guests gets messed up. The only workaround that I've found for this is to run
```
VBoxManage modifyvm "VM name" --natnet1 "192.168/16"
```
as per the [VirtualBox fine-tuning NAT documentation](https://www.virtualbox.org/manual/ch09.html#changenat). But I would have to run this command for each instance, each time a do a `boxfuse run`. *Perhaps there is a better way?*
But even with this in place, I still would have some issues with the port mapping. For AWS deploy, each service exposes the same two ports, one port for regular HTTP traffic and another for administration and health-checks. For the sake of simplicity, I would prefer to have the same setup in `dev`, this of course, leads to collisions, which from what I can tell, Boxfuse solves seamlessly for me, but with the slight inconvenience of having services start on different ports depending on when I launch them.

Even if I get this to work properly, however, I'm afraid there's yet another issue that I would need to resolve. When an instance registers with Eureka it'll register with its IP, in this case probably something like `192.168.0.5` (after issuing the command given in the fine-tuning documentation) and this will be the same for all instances that registers. I gather from your response that it should still work, having `Guest A` listening on `192.168.0.5:8000` to be able to communicate with `Guest B` listening on `192.168.0.5:9000`, but I can't get it to work properly. Having `Guest A` communicate with `Guest B` on `$BOXFUSE_HOST_IP:9000` and vice versa works, however.
The only workaround I can figure for this would be to have each instance register with Eureka using the `$BOXFUSE_HOST_IP`, going about it that way might work, but doesn't seem to be anything Eureka supports out of the box.

I fully realize this is not a forum for VirtualBox support and if I'm going about this the wrong way, or if the communication between nodes, as in my example above, should work, please let me know and I'll try and troubleshoot why it does not work in my setup. But I still believe there could be a good case for the proposal, as it would allow a setup locally that fairly closely reflects the AWS setup hinted at in https://github.com/boxfuse/boxfuse-issues/issues/47 where there is no need for a load balancer and communication between instances is handled directly with routing provided by Eureka. The network configuration being handled in this case through VirtualBox's Host-only network as it would be through the VPC configuration on AWS.

**Comment by axelfontaine** [comment]
The best way to replicate the AWS setup would actually be to use bridged networking. This way each VM gets its own IP and has full access to the outside world. This lets apps open the port they want without any need for forwarding. The only potential drawback is that this could potentially consume a lot of DHCP addresses on your network.

Alternatively the new experimental [Network NAT](https://www.virtualbox.org/manual/ch06.html#network_nat_service) could also be a potential option. You would still need port forwarding to access services from the host, but they could communicate among each other without special tricks.

Would either of these two be a good fit for you?

Ideally we want to aim for a solution that "just works" for our users without the need for any additional configuration if possible.

**Comment by axelfontaine** [comment]
Come to think of it, can elaborate a bit on how exactly VirtualBox 's dhcp conflicts on your machine?

**Comment by axelfontaine** [comment]
We investigated this some more today and it seems we unfortunately have to rule out the VirtualBox natnetwork option as there is no way to externally retrieve the IP of a VM. We filed an issue with VirtualBox to track this: https://www.virtualbox.org/ticket/15449

However there may be an easy solution for Eureka as documented here: http://stackoverflow.com/questions/30349811/register-to-eureka-from-docker-with-a-custom-ip

Can you share the details on how exactly VirtualBox 's dhcp conflicts on your machine? (We want to investigate whether we could resolve those kind of conflicts automatically instead of having to introduce a config property)

**Comment by axelfontaine** [comment]
Starting with Boxfuse Client 1.21.0.1079, for VirtualBox 5.1 and newer (we discovered too many stability issues with previous versions) Boxfuse will now use VirtualBox NAT Networking where each instance gets its own IP and all instances can communicate directly with each other in an own virtual network, yet can still be made accessible via port forwarding.

See https://boxfuse.com/docs/virtualbox#networking
