### ISSUE TITLE
Node v4 or Node v6

### ISSUE THREAD

**Issue by lizell** [boxfuse/boxfuse-issues#85]
I'm wondering if there are any plans to support different node versions? I have one app that currently has to be on node 4.2 or lower and an other app that runs into problems with node 5 but is OK on node 6.

Currently only node 5.9.1 is supported and that is an odd number release with no LTS. See https://github.com/nodejs/LTS#lts_schedule. It would be great to have say the last two LTS releases of node available.

Please let me know if I can contribute with them in any way.

**Comment by axelfontaine** [comment]
We have now made version 6.2.0 available. You can see which versions are currently available using `boxfuse inventory nodejs` and you can select a specific version using `-components.nodejs=6.2.0` when fusing an image.

I am leaving this open as we'll be making a number of other enhancements soon.

**Comment by axelfontaine** [comment]
Boxfuse Client 1.19.4.967 now added support for all current LTS releases. Enjoy!

**Comment by axelfontaine** [comment]
We have just released two additional features:

- Node.js engine version autodetection from package.json: https://boxfuse.com/docs/payloads/nodejs#version
- Live reloading: https://boxfuse.com/blog/live-reloading

Enjoy!

**Comment by lizell** [comment]
Great!! :+1:
