### ISSUE TITLE
Add confirm dialog to 'kill' button in Console

### ISSUE THREAD

**Issue by herder** [boxfuse/boxfuse-issues#90]
The 'Kill' button for an app executes immediately, with no possibility of aborting.

We should get an "Are you sure" dialog of some sort, to prevent accidentally killing an app.
Something like Heroku's "Type the name of the app you want to kill" would be even better!

**Comment by axelfontaine** [comment]
That certainly makes sense.

A simple "Are you sure?" is probably enough for kill as you can quickly reverse that with run.

However having to type the name is probably a better idea for destroy, which is not so easily reversible.

What do you think?

**Comment by herder** [comment]
Ah, I didn't know you could reverse it directly! That would be great feedback after pressing 'kill' in any case. But yes, if it's reversible an 'Are you sure' is sufficient, I think.

And +1 for typing name when destroying an app.

**Comment by axelfontaine** [comment]
Well not directly directly, but as soon as the kill operation finishes. This still incurs 1-2 minutes of downtime, but it is nowhere near as critical as destroy.

**Comment by herder** [comment]
Ok. This could be painful, but I agree that destroy is worse.

At any rate: if we risk downtime due to misclicking, I think I'd like a 'write app name' confirm on the 'Kill' button, too. It's a pretty rare usecase, so I'd say it's worth the inconvenience.

**Comment by axelfontaine** [comment]
This feature is now implemented and available for you to use. The kill action has a simple one-click confirmation and the destroy action now requires you to type the app name.

Enjoy!
