### ISSUE TITLE
Sort subnets by name

### ISSUE THREAD

**Issue by herder** [boxfuse/boxfuse-issues#91]
I'd like the subnets in the Console to be sorted by name (if they have one). 
That way, we can use naming conventions to get a clearer view of which subnets to map to an app.

**Comment by axelfontaine** [comment]
Just to clarify, for the following subnets (current rendering):

- subnet-12345678
- subnet-20000000 (My Subnet)
- subnet-21000000 (TTT)
- subnet-30000000 (AAA)

the order and rendering style would be changed to:

- AAA (subnet-30000000)
- My Subnet (subnet-20000000)
- subnet-12345678
- TTT (subnet-21000000)

Correct?

**Comment by herder** [comment]
Correct :)
The subnet id:s are not very human-readable-or-memorable anyway, so this would make the UI much clearer IMHO.

**Comment by axelfontaine** [comment]
This feature is now implemented and available for you to use.

Enjoy!
