### ISSUE TITLE
blue/green deployment did not update security group

### ISSUE THREAD

**Issue by jtheuer** [boxfuse/boxfuse-issues#92]
Hi,

I created the elb and security groups manually (cloudformation). I had to change the security group and updated my boxfuse.conf file:

```
securitygroup=sg-20b1d447
```

and started a blue/green deployment with:

```
boxfuse run -env=production -configfile=boxfuse.conf
```

However, the new launch config contained the old security group. (And couldn't be reached from the ELB) 

EDIT: I think the root cause is that I don't know which settings in the config file belong to which boxfuse command. I probably just expected that I can change things like securitygroup, instance profile per deploy. A possible solution would be to just add the info to the boxfuse.conf.

I basically re-created everything now because the system wasn't in use, yet.
But is it possible to change the security group without downtime and what should I have done.? 

Jan

**Comment by axelfontaine** [comment]
Thank you Jan. This is officially supported (see https://boxfuse.com/docs/commandline/run) and should work. We'll investigate and get back to you.

**Comment by axelfontaine** [comment]
Thank you for your patience Jan. We investigated this and tried multiple times, but couldn't reproduce the issue.

To make it easier to see what is happening we have added additional debug output that shows the security group being used.

Additionally we have also updated our docs for the command line client to include the exact name of each boxfuse.conf property: https://boxfuse.com/docs/commandline/fuse#settings

 Please reopen if it shows up again.
