### ISSUE TITLE
Possible Boxfuse or AWS api race condition

### ISSUE THREAD

**Issue by HunterSherms** [boxfuse/boxfuse-issues#93]
We're noticing what we assume is a race condition when destroying and then attempting to re-create boxfuse images within the same bash script.

`boxfuse rm myapp`
  Boxfuse client v.1.20.0.1018
  Copyright 2016 Boxfuse GmbH. All rights reserved.
  Account: username (Firstname Lastname)
  Removing all locally available Images of username/myapp ...
  Removing Image username/myappi:0.0.7 ...
  All locally available Images of username/myapp removed in 00:00.001s

`boxfuse rm myapp:0.0.7 -vault true`
  Boxfuse client v.1.20.0.1018
  Copyright 2016 Boxfuse GmbH. All rights reserved.
  Account: username (Firstname Lastname)
  Removing username/myapp:0.0.7 from the Boxfuse Vault ...
  Deregistering ami-XXXXXXXX ...
  Removed Image: username/myapp:0.0.7
  Successfully removed 1 images from the Boxfuse Vault for myapp.

`boxfuse fuse application/target/myapp-0.0.7.jar`
  Boxfuse client v.1.20.0.1018
  Copyright 2016 Boxfuse GmbH. All rights reserved.
  Account: username(Firstname Lastname)
  Fusing Image for myapp-0.0.7.jar ...
  Image fused in 00:24.629s (163735 K) -> username/myapp:0.0.7

`boxfuse push myapp:0.0.7`
  Boxfuse client v.1.20.0.1018
  Copyright 2016 Boxfuse GmbH. All rights reserved.
  Account: username (Firstname Lastname)
  Pushing username/myapp:0.0.7 ...
  Verifying username/myapp:0.0.7 ...

`boxfuse convert myapp:0.0.7`
  Boxfuse client v.1.20.0.1018
  Copyright 2016 Boxfuse GmbH. All rights reserved.
  Account: username (Firstname Lastname)
  Already converted username/myapp:0.0.7 in us-east-1 -> ami-XXXXXXXX

It appears to still think the ami exists despite us having just destroyed it.

**Comment by axelfontaine** [comment]
We did quite a bit of testing and can confirm numerous eventual consistency issues via the AWS API regarding AMI status. We are continuing to investigate and will get back to you.

**Comment by axelfontaine** [comment]
We are now 100% certain this is an AWS eventual consistency issue (we saw propagation delays of up to 3 minutes!) and have filed a support case with them with exact steps how to reproduce. We'll keep you updated.

**Comment by HunterSherms** [comment]
Hey @axelfontaine - 

We've added a sleep 180 in between our "boxfuse convert" and trying to attach the AMI to an AWS launchconfig and are still seeing "CreateLaunchConfiguration operation: AMI cannot be described" in about 25% of launches. Did you ever hear anything back from AWS?

**Comment by HunterSherms** [comment]
This bit of Bash seems to have solved the issue for us:

```bash
echo "Waiting for AMI to appear on AWS CLI"
#Wait until the AMI shoes up in the AWS CLI
for i in $(seq 1 10); do

    DESCRIBE_IMAGE=$(aws ec2 describe-images --image-ids "$AMI" --region us-east-1)
    AMICOUNT=$(echo "$DESCRIBE_IMAGE" | jq -r '[.Images[]] | length')
    if [ "$AMICOUNT" -gt 0 ]
    then
        echo "AMI $AMI discoverable"
        break
    else
        if [ "$i" -eq 10 ]; then
            echo "Unable to discover AMI after 5 minutes"
            exit 1;
        else
            echo "Iteration $i - Sleeping for 30 seconds"
            sleep 30
    	fi
    fi
done
```

**Comment by axelfontaine** [comment]
@HunterSherms Even though we can clearly reproduce this, AWS support still has trouble doing so. Happy to hear you have a workaround for now though.

**Comment by axelfontaine** [comment]
We have now implemented additional mitigation measures that prevent this.
