### ISSUE TITLE
Support default environment configuration files

### ISSUE THREAD

**Issue by therk** [boxfuse/boxfuse-issues#95]
It would be very helpful to have default environment specific configuration file, as different environment  would have different configurations such as security groups, database, logging, S3, etc.
Currently there are three configuration files that are check:
[boxfuse_install_dir]/conf/boxfuse.conf
~/.boxfuse/boxfuse.conf
./boxfuse.conf

It would be good to check and load:
~/.boxfuse/boxfuse.conf
~/.boxfuse/boxfuse.[env].conf
./boxfuse.conf
./boxfuse.[env].conf

So, when I run "boxfuse run -env=test" the following files will be loaded:
~/.boxfuse/boxfuse.conf
~/.boxfuse/boxfuse.test.conf
./boxfuse.conf
./boxfuse.test.conf

**Comment by axelfontaine** [comment]
That makes a lot of sense and it's a nice low-hanging fruit :+1:

**Comment by axelfontaine** [comment]
Just as an aside, one option available today is to actually specify the config file to use with the `-configfile=...` argument (see https://boxfuse.com/docs/commandline/#general)

**Comment by therk** [comment]
That is what I currently use and have a file per environment. Having a default would reduce number of parameters I have to specify. Also, it would help with my SBT plugin and the generation of the configuration file per environment.

**Comment by axelfontaine** [comment]
This is now implemented in Boxfuse Client 1.20.3.1034 (See https://boxfuse.com/docs/commandline/#overriding for the exact naming convention and overriding order)
