### ISSUE TITLE
Allow hosting private Boxfuse Vault using own S3 bucket

### ISSUE THREAD

**Issue by HunterSherms** [boxfuse/boxfuse-issues#96]

**Comment by axelfontaine** [comment]
I am currently unsure whether we'll go down this path. The alternative we're considering is to give customers the option to let Boxfuse use one of their S3 buckets on their account to host their own images.

Would that work for you?

**Comment by HunterSherms** [comment]
Any path that allows us to maintain ownership of our code and config files throughout the deployment pipeline will work for us.

Sending the above through a third party will be a hard sell for our security conscious clients.

**Comment by brodziakm** [comment]
I'd be very keen on hosting our AMIs on our own S3 bucket.

**Comment by axelfontaine** [comment]
@brodziakm AMIs are already 100% on your AWS account and fully encrypted. This is about the images used to create them, which are currently stored in the Boxfuse Vault.

**Comment by axelfontaine** [comment]
This has now been implemented: https://boxfuse.com/blog/private-vault
