### ISSUE TITLE
Environment variables with spaces are passed incorrectly 

### ISSUE THREAD

**Issue by sery0ga** [boxfuse/boxfuse-issues#99]
For example, I have a command like this:

`boxfuse run test -jvm.args=-Dconfig.file=conf/application-stage.conf -envvars.MAIL_FROM="Test Buddy <no-reply@example.com>"`

Unfortunately, boxfuse converts the environment variable MAIL_FROM to 

` '-DMAIL_FROM=Test' '-DBuddy' '-D<no-reply@example.com>'`

I tried several variants:

- `"Test Buddy <no-reply@example.com>"`
- `'"Test Buddy <no-reply@example.com>"'`
- `"'Test Buddy <no-reply@example.com>'"`
- `"\"Test Buddy <no-reply@example.com>\""`
- `"Test\ Buddy\ <no-reply@example.com>"`

None of them worked. So it's not possible to pass environment variables containing spaces which is quite frustrating when you're moving from another services like Heroku.

**Comment by axelfontaine** [comment]
Thanks for pointing this out!

The environment variables is actually getting passed correctly and you can access it via `System.getenv("MAIL_FROM")`. What was wrong here is the convenience feature that exposes the environment variable as a system property.

This has now been fixed and will be released as part of Boxfuse Client 1.20.5 which will be available later today.
